"use client";

import {
	A2UICallCard,
	type FileAttachment,
	FileAttachmentChip,
	FileMentionPopup,
	ReadAloudButton,
	SlashCommandPopup,
	ToolCallCard,
	ToolCallGroup,
	getToolIcon,
} from "@/components/chat";
import { BrailleSpinner } from "@/components/common";
import { useChatContext } from "@/components/contexts/chat-context";
import {
	ContextWindowGauge,
	CopyButton,
	MarkdownRenderer,
} from "@/components/data-display";
import { Button } from "@/components/ui/button";
import {
	ContextMenu,
	ContextMenuContent,
	ContextMenuItem,
	ContextMenuTrigger,
} from "@/components/ui/context-menu";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
	Popover,
	PopoverContent,
	PopoverTrigger,
} from "@/components/ui/popover";
import { DictationOverlay } from "@/components/voice";
import {
	VoiceMenuButton,
	type VoiceMode,
} from "@/components/voice/VoiceMenuButton";
import type { Features, PiModelInfo } from "@/features/chat/api";
import { InstructionsPinnedMessage } from "@/features/chat/components/InstructionsPinnedMessage";
import { TimelineTreeView } from "@/features/chat/components/TimelineTreeView";
import {
	buildLegacyDraftStorageKey,
	buildSessionDraftStorageKey,
} from "@/features/chat/hooks/draft-storage";
import {
	normalizeTokenCount,
	parsePiSessionStats,
} from "@/features/chat/utils/session-stats";
import { type A2UISurfaceState, useA2UI } from "@/hooks/use-a2ui";
import { useDictation } from "@/hooks/use-dictation";
import { useWorkspaceInstructions } from "@/hooks/use-workspace-instructions";
import {
	type DisplayMessage,
	type DisplayPart,
	getCachedScrollPosition,
	setCachedScrollPosition,
	useChat,
} from "@/hooks/useChat";
import { workspaceFileUrl } from "@/lib/api/files";
import type { Part, ToolStatus } from "@/lib/canonical-types";
import {
	type ChatFileAdapter,
	MessageGroupCard,
} from "@/lib/chat-rendering/CanonicalMessageRenderer";
import { stripAnsiSequences } from "@/lib/chat-rendering/chat-render-text";
import {
	type MessageGroup,
	groupMessages,
} from "@/lib/chat-rendering/group-messages";
import { useChatVerbosity } from "@/lib/chat-verbosity";
import { insertFileMention } from "@/lib/file-mention";
import { extractFileReferenceDetails, getFileTypeInfo } from "@/lib/file-types";
import { downloadFileMux, uploadFileMux } from "@/lib/mux-files";
import {
	formatSessionDate,
	formatTempId,
	getDisplayPiTitle,
	getTempIdFromSession,
	normalizeWorkspacePath,
	parseAutoGeneratedTitle,
} from "@/lib/session-utils";
import {
	type SlashCommand,
	fuzzyMatch,
	parseSlashInput,
} from "@/lib/slash-commands";
import {
	type StreamingPresentationMode,
	useStreamingPresentation,
} from "@/lib/streaming-presentation";
import { getToolSummary } from "@/lib/tool-summaries";
import { cn } from "@/lib/utils";

import { AgentErrorBody } from "@/features/chat/components/AgentErrorBody";
import { getWsManager } from "@/lib/ws-manager";
import {
	ArrowDown,
	ArrowUp,
	Bot,
	Check,
	Copy,
	Download,
	ExternalLink,
	FileCode,
	FileImage,
	FileText,
	FileVideo,
	GitBranch,
	Loader2,
	PaintBucket,
	Paperclip,
	Send,
	StopCircle,
	Trash2,
	User,
} from "lucide-react";
import {
	type ChangeEvent,
	type KeyboardEvent,
	memo,
	startTransition,
	useCallback,
	useEffect,
	useLayoutEffect,
	useMemo,
	useRef,
	useState,
} from "react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";

function stringifyForMarkdown(value: unknown): string {
	if (typeof value === "string") return stripAnsiSequences(value);
	if (value === null || value === undefined) return "";
	try {
		return stripAnsiSequences(JSON.stringify(value, null, 2));
	} catch {
		return stripAnsiSequences(String(value));
	}
}

const LEGACY_CHAT_FILE_ADAPTER: ChatFileAdapter = {
	fileUrl: workspaceFileUrl,
	downloadFile: downloadFileMux,
	renderReadAloud: (text) => (
		<ReadAloudButton text={text} className="ml-1 flex-shrink-0" />
	),
};

function safeFileStem(value: string): string {
	const stem = value
		.toLowerCase()
		.trim()
		.replace(/[^a-z0-9._-]+/g, "-")
		.replace(/^-+|-+$/g, "");
	return stem || "session";
}

/** Todo item structure (matching todowrite tool) */
export interface TodoItem {
	id: string;
	content: string;
	status: "pending" | "in_progress" | "completed" | "cancelled";
	priority: "high" | "medium" | "low";
}

type QueuedMessage = {
	id: string;
	text: string;
};

type ForkPoint = {
	entry_id: string;
	role?: string;
	preview: string;
};

export const INITIAL_VISIBLE_MESSAGE_COUNT = 30;
export const LOAD_MORE_MESSAGE_COUNT = 30;

export function nextVisibleMessageCount(
	current: number,
	total: number,
): number {
	return Math.min(current + LOAD_MORE_MESSAGE_COUNT, total);
}

export interface ChatViewProps {
	/** Current locale */
	locale?: "en" | "de";
	/** Class name for container */
	className?: string;
	/** Storage key prefix for cached messages */
	storageKeyPrefix?: string;
	/** Features config (for voice settings) */
	features?: Features | null;
	/** Workspace path for file operations */
	workspacePath?: string | null;
	/** Assistant name to display (user-configured default chat name) */
	assistantName?: string | null;
	/** Hide the internal header (used when embedded in sessions app with external header) */
	hideHeader?: boolean;
	/** Display name of the current user (for shared workspace sender labels). */
	senderName?: string | null;
	/** Callback to report token usage (for external gauge display) */
	onTokenUsageChange?: (usage: {
		inputTokens: number;
		outputTokens: number;
		maxTokens: number;
	}) => void;
	/** Selected session ID (from sidebar) */
	selectedSessionId?: string | null;
	/** Callback when selection should change (e.g. /new created a session) */
	onSelectedSessionIdChange?: (id: string | null) => void;
	/** Message ID to scroll to (from search results) */
	scrollToMessageId?: string | null;
	/** Callback when scroll target is reached (to clear the target) */
	onScrollToMessageComplete?: () => void;
	/** Callback when a message is sent (for sidebar refresh) */
	onMessageSent?: () => void;
	/** Callback when an assistant message completes (for sidebar refresh) */
	onMessageComplete?: () => void;
	/** Callback after a Fork is durably visible as a child Session. */
	onSessionForked?: () => void;
	/** Callback when todos change (extracted from Pi todowrite tool calls) */
	onTodosChange?: (todos: TodoItem[]) => void;
	/** Pending file attachment to add (e.g. from canvas "Save & add to chat") */
	pendingFileAttachment?: FileAttachment | null;
	/** Called after the pending file attachment has been consumed */
	onPendingFileAttachmentConsumed?: () => void;
	/** Text to prefill into the chat input (e.g. from browser "Send to chat") */
	pendingChatInput?: string | null;
	/** Called after the pending chat input has been consumed */
	onPendingChatInputConsumed?: () => void;
	/** Called when a chat file reference is activated. */
	onFileReferenceOpen?: (filePath: string) => void;
}

/**
 * Chat view using Pi agent runtime.
 */
export function ChatView({
	locale = "en",
	className,
	storageKeyPrefix,
	features,
	workspacePath,
	assistantName,
	hideHeader = false,
	senderName,
	onTokenUsageChange,
	selectedSessionId,
	onSelectedSessionIdChange,
	scrollToMessageId,
	onScrollToMessageComplete,
	onMessageSent,
	onMessageComplete,
	onSessionForked,
	onTodosChange,
	pendingFileAttachment,
	onPendingFileAttachmentConsumed,
	pendingChatInput,
	onPendingChatInputConsumed,
	onFileReferenceOpen,
}: ChatViewProps) {
	const [sendPending, setSendPending] = useState(false);
	const [sendPendingSessionId, setSendPendingSessionId] = useState<
		string | null
	>(null);
	const sendPendingTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(
		null,
	);
	const normalizedWorkspacePath = useMemo(
		() => normalizeWorkspacePath(workspacePath),
		[workspacePath],
	);
	const instructionsContent = useWorkspaceInstructions(normalizedWorkspacePath);

	const resolvedStorageKeyPrefix =
		storageKeyPrefix ??
		`oqto:workspacePi:${(normalizedWorkspacePath ?? "default").replace(
			/[^a-zA-Z0-9._-]+/g,
			"_",
		)}`;
	const legacyDraftStorageKey = buildLegacyDraftStorageKey(
		resolvedStorageKeyPrefix,
	);
	const draftStorageKey = buildSessionDraftStorageKey(
		resolvedStorageKeyPrefix,
		selectedSessionId,
	);
	const scrollStorageKey = `${resolvedStorageKeyPrefix}:scrollPosition`;
	const { updateChatSessionTitleLocal, selectedChatFromHistory } =
		useChatContext();
	const sessionMeta = selectedChatFromHistory ?? null;
	const handleMessageComplete = useCallback(() => {
		onMessageComplete?.();
	}, [onMessageComplete]);
	const {
		messages,
		isConnected,
		isStreaming,
		isAwaitingResponse,
		error,
		promptQueue,
		historyHydrated,
		historyLoading,
		send,
		appendLocalAssistantMessage,
		abort,
		compact,
		newSession,
		resetSession,
		state: piState,
		refresh,
	} = useChat({
		workspacePath: normalizedWorkspacePath,
		storageKeyPrefix: resolvedStorageKeyPrefix,
		selectedSessionId,
		senderName,
		onSelectedSessionIdChange,
		onMessageComplete: handleMessageComplete,
		onTitleChanged: updateChatSessionTitleLocal,
	});
	// Refresh messages when backfill completes (signalled via DOM event).
	// useeffect-guardrail: allow — listening for custom DOM event from backfill, no hook covers this
	useEffect(() => {
		const handler = () => void refresh();
		window.addEventListener("oqto:backfill-complete", handler);
		return () => window.removeEventListener("oqto:backfill-complete", handler);
	}, [refresh]);

	// Draft persistence - restore from localStorage on mount.
	// Input value lives in a ref (never in React state) so that
	// keystrokes never trigger a React render of this large component.
	// The textarea uses defaultValue and is fully uncontrolled.
	const inputInitialValue = useMemo(() => {
		if (typeof window === "undefined") return "";
		try {
			return localStorage.getItem(draftStorageKey) || "";
		} catch {
			return "";
		}
	}, [draftStorageKey]);
	const inputValueRef = useRef(inputInitialValue);
	// Lightweight state only for send-button enabled/disabled
	const [canSendInput, setCanSendInput] = useState(!!inputInitialValue.trim());
	// Helper to imperatively set the textarea value and sync ref
	const setInput = useCallback((value: string) => {
		inputValueRef.current = value;
		if (inputRef.current) {
			inputRef.current.value = value;
		}
		startTransition(() => setCanSendInput(!!value.trim()));
	}, []);
	const [fileAttachments, setFileAttachments] = useState<FileAttachment[]>([]);

	// Consume pending file attachment from external source (e.g. canvas)
	useEffect(() => {
		if (pendingFileAttachment) {
			setFileAttachments((prev) => {
				// Avoid duplicates
				if (prev.some((a) => a.path === pendingFileAttachment.path))
					return prev;
				return [...prev, pendingFileAttachment];
			});
			onPendingFileAttachmentConsumed?.();
		}
	}, [pendingFileAttachment, onPendingFileAttachmentConsumed]);

	const [queuedMessages, setQueuedMessages] = useState<QueuedMessage[]>([]);
	const messagesEndRef = useRef<HTMLDivElement>(null);
	const messagesContainerRef = useRef<HTMLDivElement>(null);
	const inputRef = useRef<HTMLTextAreaElement>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);
	const queueSendInFlightRef = useRef(false);
	const queueCooldownRef = useRef<number | null>(null);
	const lastScrollTopRef = useRef<number | null>(null);
	const lastScrollHeightRef = useRef<number | null>(null);
	const draftSaveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(
		null,
	);
	const initialScrollDoneRef = useRef(false);
	const [forkListOpen, setForkListOpen] = useState(false);
	const [forkPoints, setForkPoints] = useState<ForkPoint[]>([]);
	const [forkPointsLoading, setForkPointsLoading] = useState(false);
	const [forkingEntryId, setForkingEntryId] = useState<string | null>(null);

	const loadForkPoints = useCallback(async () => {
		if (!selectedSessionId) {
			toast.error("No active chat session.");
			return [] as ForkPoint[];
		}
		setForkPointsLoading(true);
		try {
			// Ensure a live Pi session exists (history-only sessions need resume first).
			const ws = getWsManager();
			ws.agentCreateSession(selectedSessionId);
			await ws.waitForSessionReady(selectedSessionId, 6000);

			const points = await ws.agentGetForkPoints(selectedSessionId);
			setForkPoints(points);
			return points;
		} catch (err) {
			toast.error(
				err instanceof Error ? err.message : "Failed to load fork points.",
			);
			return [] as ForkPoint[];
		} finally {
			setForkPointsLoading(false);
		}
	}, [selectedSessionId]);

	const handleForkAtEntry = useCallback(
		async (entryId: string) => {
			if (!selectedSessionId) {
				toast.error("No active chat session.");
				return;
			}
			setForkingEntryId(entryId);
			try {
				// History-only sessions are not necessarily live in the runner.
				// Fork must wait for session.create readiness; sending both
				// concurrently races and the runner correctly rejects the fork as
				// PiSessionNotFound. Keep this preflight on every fork entry point.
				const ws = getWsManager();
				ws.agentCreateSession(selectedSessionId);
				await ws.waitForSessionReady(selectedSessionId, 6000);
				const result = await ws.agentFork(selectedSessionId, entryId);
				if (result.cancelled) {
					toast.info("Fork cancelled.");
					return;
				}
				setForkListOpen(false);
				if (result.new_session_id && onSelectedSessionIdChange) {
					// Pi forks before the selected user prompt and returns that
					// prompt for editing in the independent child Session. Persist
					// it under the child's draft key before changing selection so
					// the session-change draft loader cannot erase it.
					if (result.text && typeof window !== "undefined") {
						localStorage.setItem(
							buildSessionDraftStorageKey(
								resolvedStorageKeyPrefix,
								result.new_session_id,
							),
							result.text,
						);
					}
					onSessionForked?.();
					onSelectedSessionIdChange(result.new_session_id);
					toast.success("Forked to a new independent session.");
				} else {
					await refresh();
					toast.success("Fork created.");
				}
			} catch (err) {
				toast.error(
					err instanceof Error ? err.message : "Failed to fork session.",
				);
			} finally {
				setForkingEntryId(null);
			}
		},
		[
			selectedSessionId,
			refresh,
			onSelectedSessionIdChange,
			onSessionForked,
			resolvedStorageKeyPrefix,
		],
	);

	// Consume pending chat input from external source (e.g. browser "Send to chat")
	// biome-ignore lint/correctness/useExhaustiveDependencies: setInput is stable setState
	useEffect(() => {
		if (pendingChatInput) {
			setInput(pendingChatInput);
			onPendingChatInputConsumed?.();
			// Focus the input after a tick so the user can review/edit
			setTimeout(() => {
				inputRef.current?.focus();
			}, 100);
		}
	}, [pendingChatInput, onPendingChatInputConsumed]);

	// biome-ignore lint/correctness/useExhaustiveDependencies: setInput is stable setState
	useEffect(() => {
		if (typeof window === "undefined") return;
		try {
			const sessionDraft = localStorage.getItem(draftStorageKey);
			if (sessionDraft !== null) {
				setInput(sessionDraft);
				return;
			}

			// One-time migration from legacy workspace-scoped draft key.
			const legacyDraft = localStorage.getItem(legacyDraftStorageKey);
			if (legacyDraft !== null) {
				localStorage.setItem(draftStorageKey, legacyDraft);
				localStorage.removeItem(legacyDraftStorageKey);
				setInput(legacyDraft);
				return;
			}

			setInput("");
		} catch {
			setInput("");
		}
	}, [draftStorageKey, legacyDraftStorageKey]);
	const sendPendingRef = useRef(sendPending);
	sendPendingRef.current = sendPending;
	useEffect(() => {
		// Reset queue when session changes; use void to reference the dep
		void selectedSessionId;
		setQueuedMessages([]);
		if (!sendPendingRef.current) {
			setSendPendingSessionId(null);
		}
	}, [selectedSessionId]);

	useEffect(() => {
		const handler = () => {
			setForkListOpen(true);
			void loadForkPoints();
		};
		window.addEventListener("oqto:open-fork-list", handler);
		return () => window.removeEventListener("oqto:open-fork-list", handler);
	}, [loadForkPoints]);
	useEffect(() => {
		if (!selectedSessionId || !piState?.sessionName) return;
		// Only apply the title if piState actually belongs to this session.
		// If piState has no sessionId, we can't verify ownership — skip to
		// avoid applying a stale title from a previous session.
		if (!piState.sessionId || piState.sessionId !== selectedSessionId) return;
		// Parse the raw Pi title to strip "workspace:" prefix and "[readable-id]" suffix
		const parsed = parseAutoGeneratedTitle(piState.sessionName);
		updateChatSessionTitleLocal(
			selectedSessionId,
			parsed.title || piState.sessionName,
			parsed.readable_id,
		);
	}, [
		piState?.sessionName,
		piState?.sessionId,
		selectedSessionId,
		updateChatSessionTitleLocal,
	]);
	useEffect(() => {
		if (isStreaming || isAwaitingResponse) {
			setSendPending(false);
			setSendPendingSessionId(null);
		}
	}, [isAwaitingResponse, isStreaming]);
	useEffect(() => {
		if (!sendPending || isStreaming || isAwaitingResponse) {
			if (sendPendingTimeoutRef.current) {
				clearTimeout(sendPendingTimeoutRef.current);
				sendPendingTimeoutRef.current = null;
			}
			return;
		}
		if (!sendPendingTimeoutRef.current) {
			sendPendingTimeoutRef.current = setTimeout(() => {
				setSendPending(false);
				setSendPendingSessionId(null);
			}, 8000);
		}
		return () => {
			if (sendPendingTimeoutRef.current) {
				clearTimeout(sendPendingTimeoutRef.current);
				sendPendingTimeoutRef.current = null;
			}
		};
	}, [isAwaitingResponse, isStreaming, sendPending]);
	const [showFileMentionPopup, setShowFileMentionPopup] = useState(false);
	const [fileMentionQuery, setFileMentionQuery] = useState("");
	const [showSlashPopup, setShowSlashPopup] = useState(false);
	const [hideRecoveredErrors, setHideRecoveredErrors] = useState<boolean>(
		() => {
			if (typeof window === "undefined") return false;
			try {
				return localStorage.getItem("oqto:hideRecoveredErrors") === "1";
			} catch {
				return false;
			}
		},
	);
	// useeffect-guardrail: allow - sync recovered-error preference from settings sidebar
	useEffect(() => {
		const readSetting = () => {
			try {
				setHideRecoveredErrors(
					localStorage.getItem("oqto:hideRecoveredErrors") === "1",
				);
			} catch {
				// ignore read failures
			}
		};

		const onStorage = (event: StorageEvent) => {
			if (event.key === "oqto:hideRecoveredErrors") {
				readSetting();
			}
		};

		window.addEventListener("storage", onStorage);
		window.addEventListener("oqto:chat-ui-settings-updated", readSetting);
		return () => {
			window.removeEventListener("storage", onStorage);
			window.removeEventListener("oqto:chat-ui-settings-updated", readSetting);
		};
	}, []);
	const showPromptQueueDebug = useMemo(() => {
		if (typeof window === "undefined") return false;
		try {
			return localStorage.getItem("debug:oqto-queue") === "1";
		} catch {
			return false;
		}
	}, []);
	const { mode: streamingPresentationMode } = useStreamingPresentation();
	const [voiceMode, setVoiceMode] = useState<VoiceMode>(null);
	const [isUploading, setIsUploading] = useState(false);
	const [availableModels, setAvailableModels] = useState<PiModelInfo[]>([]);
	const [selectedModelRef, setSelectedModelRef] = useState<string | null>(null);
	const [isSwitchingModel, setIsSwitchingModel] = useState(false);
	const [modelQuery, setModelQuery] = useState("");
	const [commandError, setCommandError] = useState<Error | null>(null);
	const [customCommands, setCustomCommands] = useState<SlashCommand[]>([]);
	const [sessionTokens, setSessionTokens] = useState<{
		input: number;
		output: number;
	} | null>(null);
	const [isUserScrolled, setIsUserScrolled] = useState(
		() => getCachedScrollPosition(scrollStorageKey) !== null,
	);
	const isUserScrolledRef = useRef(isUserScrolled);
	// Set to true by wheel/touch/pointer events on the container.
	// Cleared on send and jump-to-bottom. Only while this is true does
	// the scroll event handler update isUserScrolled state.
	const userInitiatedScrollRef = useRef(false);
	const programmaticScrollRef = useRef(false);
	const scrollToBottomRafRef = useRef<number | null>(null);

	const scrollToBottom = useCallback(() => {
		if (scrollToBottomRafRef.current !== null) return;
		scrollToBottomRafRef.current = window.requestAnimationFrame(() => {
			scrollToBottomRafRef.current = null;
			const container = messagesContainerRef.current;
			if (!container) return;
			const targetTop = Math.max(
				0,
				container.scrollHeight - container.clientHeight,
			);
			const distanceToBottom = targetTop - container.scrollTop;
			// Avoid redundant writes at/near bottom; they can trigger scroll-event
			// churn and visible flicker while streaming updates arrive quickly.
			if (Math.abs(distanceToBottom) < 2) return;
			programmaticScrollRef.current = true;
			container.scrollTop = targetTop;
			lastScrollTopRef.current = container.scrollTop;
			lastScrollHeightRef.current = container.scrollHeight;
		});
	}, []);

	// Keep initial chat paint bounded. The previous Math.max(messages.length,
	// 30) initialized and expanded this window to the complete history, making
	// the "load more" path unreachable and rendering multi-megabyte chats in
	// one main-thread task.
	const [visibleCount, setVisibleCount] = useState(
		INITIAL_VISIBLE_MESSAGE_COUNT,
	);
	// biome-ignore lint/correctness/useExhaustiveDependencies: the session id is intentionally the reset trigger even though the reset value is constant.
	useEffect(() => {
		setVisibleCount(INITIAL_VISIBLE_MESSAGE_COUNT);
	}, [selectedSessionId]);

	// A2UI integration - adapt Pi messages to expected format
	const a2uiMessagesRef = useRef<Array<{ info: { id: string; role: string } }>>(
		[],
	);
	// Keep ref in sync with messages
	a2uiMessagesRef.current = messages.map((m) => ({
		info: { id: m.id, role: m.role },
	}));

	const {
		surfaces: a2uiSurfaces,
		handleAction: handleA2UIAction,
		getUnanchoredSurfaces,
	} = useA2UI(a2uiMessagesRef, {
		onSurfaceReceived: useCallback(() => {
			// Auto-scroll when A2UI surface arrives
			if (!isUserScrolledRef.current) {
				scrollToBottom();
			}
		}, [scrollToBottom]),
	});

	// Memoized map of message ID to surfaces to avoid creating new arrays on each render
	// Also track "orphaned" surfaces whose anchor doesn't match any current message
	const { surfacesByMessageId, orphanedSurfaces } = useMemo(() => {
		const map = new Map<string, A2UISurfaceState[]>();
		const messageIds = new Set(messages.map((m) => m.id));
		const orphaned: A2UISurfaceState[] = [];

		for (const surface of a2uiSurfaces) {
			if (surface.anchorMessageId && messageIds.has(surface.anchorMessageId)) {
				const existing = map.get(surface.anchorMessageId) || [];
				existing.push(surface);
				map.set(surface.anchorMessageId, existing);
			} else {
				// Surface has no anchor or anchor message doesn't exist
				orphaned.push(surface);
			}
		}
		return { surfacesByMessageId: map, orphanedSurfaces: orphaned };
	}, [a2uiSurfaces, messages]);

	const pendingAssistantGroupRef = useRef<MessageGroup>({
		role: "assistant",
		messages: [
			{
				id: "pending-assistant",
				role: "assistant",
				parts: [],
				timestamp: 0,
				isStreaming: true,
			},
		],
	});
	const stableGroupedMessagesRef = useRef<MessageGroup[]>([]);

	const renderedGroups = useMemo(() => {
		const visibleMessages = messages.slice(-visibleCount);
		const grouped = groupMessages(visibleMessages);
		const previous = stableGroupedMessagesRef.current;
		const stableGrouped = grouped.map((group, idx) => {
			const prev = previous[idx];
			if (
				prev &&
				prev.role === group.role &&
				prev.messages.length === group.messages.length &&
				prev.messages.every((msg, mIdx) => msg === group.messages[mIdx])
			) {
				return prev;
			}
			return group;
		});
		stableGroupedMessagesRef.current = stableGrouped;

		const lastGroup = stableGrouped[stableGrouped.length - 1];
		const lastMsg = visibleMessages[visibleMessages.length - 1];
		const isWorking =
			isStreaming ||
			isAwaitingResponse ||
			lastMsg?.isStreaming === true ||
			sendPending;
		const needsPendingAssistant =
			isWorking && (!lastGroup || lastGroup.role === "user");
		const groupsToRender = needsPendingAssistant
			? [...stableGrouped, pendingAssistantGroupRef.current]
			: stableGrouped;

		let lastAssistantIndex = -1;
		for (let i = groupsToRender.length - 1; i >= 0; i--) {
			if (groupsToRender[i]?.role === "assistant") {
				lastAssistantIndex = i;
				break;
			}
		}

		return groupsToRender.map((group, groupIndex) => {
			const groupMessageId = group.messages[0]?.id;
			const groupSurfaces = group.messages.flatMap(
				(message) => surfacesByMessageId.get(message.id) ?? [],
			);
			let modelChangeRef: string | null = null;
			if (group.role === "assistant") {
				const thisModel = getGroupModelRef(group);
				if (thisModel) {
					for (let i = groupIndex - 1; i >= 0; i--) {
						if (groupsToRender[i]?.role === "assistant") {
							const prevModel = getGroupModelRef(groupsToRender[i]);
							if (prevModel && prevModel !== thisModel) {
								modelChangeRef = thisModel;
							}
							break;
						}
					}
				}
			}

			return {
				group,
				groupIndex,
				groupMessageId,
				groupSurfaces,
				isWorking,
				isLastAssistantGroup:
					group.role === "assistant" && groupIndex === lastAssistantIndex,
				modelChangeRef,
			};
		});
	}, [
		isAwaitingResponse,
		isStreaming,
		messages,
		sendPending,
		surfacesByMessageId,
		visibleCount,
	]);

	// Extract todos from messages and notify parent.
	// Scans all messages in reverse to find the most recent todo tool call
	// or result. Both TodoWrite (input.todos) and incremental Todo actions
	// (tool_result output with todos array) are checked so that updates
	// via Todo add/update/remove are reflected immediately.
	useEffect(() => {
		if (!onTodosChange) return;

		for (let i = messages.length - 1; i >= 0; i--) {
			const msg = messages[i];
			for (let j = msg.parts.length - 1; j >= 0; j--) {
				const part = msg.parts[j];
				// Check tool_call input (TodoWrite sends full list as input)
				if (
					part.type === "tool_call" &&
					part.name?.toLowerCase().includes("todo")
				) {
					const input = part.input as Record<string, unknown> | undefined;
					if (input?.todos && Array.isArray(input.todos)) {
						onTodosChange(input.todos as TodoItem[]);
						return;
					}
				}
				// Check tool_result output (Todo add/update/remove returns
				// the full updated list in the result output)
				if (
					part.type === "tool_result" &&
					part.name?.toLowerCase().includes("todo")
				) {
					const output = part.output as
						| Record<string, unknown>
						| string
						| undefined;
					// Output can be a JSON string (from the extension's text content)
					// or already parsed as an object.
					let parsed: Record<string, unknown> | undefined;
					if (typeof output === "string") {
						try {
							parsed = JSON.parse(output);
						} catch {
							/* not JSON */
						}
					} else if (output && typeof output === "object") {
						parsed = output;
					}
					if (parsed?.todos && Array.isArray(parsed.todos)) {
						onTodosChange(parsed.todos as TodoItem[]);
						return;
					}
				}
			}
		}
		// No todos found
		onTodosChange([]);
	}, [messages, onTodosChange]);

	// Voice configuration
	const voiceConfig = useMemo(
		() =>
			(features?.voice as unknown as import("@/lib/voice/types").VoiceConfig) ??
			null,
		[features?.voice],
	);

	const currentModelRef = useMemo(() => {
		if (!piState?.model) return null;
		return `${piState.model.provider}/${piState.model.id}`;
	}, [piState?.model]);
	const canSwitchModel = Boolean(
		piState && !piState.isStreaming && !piState.isCompacting && !isStreaming,
	);
	const currentModelInfo = useMemo(() => {
		if (piState?.model) {
			return piState.model;
		}
		if (!selectedModelRef) return null;
		return (
			availableModels.find(
				(model) => `${model.provider}/${model.id}` === selectedModelRef,
			) ?? null
		);
	}, [availableModels, piState?.model, selectedModelRef]);
	const contextWindowLimit = useMemo(() => {
		if (!currentModelInfo) return 200000;
		if (currentModelInfo.contextWindow > 0) {
			return currentModelInfo.contextWindow;
		}
		if (currentModelInfo.maxTokens > 0) {
			return currentModelInfo.maxTokens;
		}
		return 200000;
	}, [currentModelInfo]);

	const modelStorageKey = useMemo(() => {
		if (!selectedSessionId) return null;
		return `oqto:chatModel:${selectedSessionId}`;
	}, [selectedSessionId]);

	useEffect(() => {
		if (!modelStorageKey) return;
		const modelRef = currentModelRef ?? selectedModelRef;
		try {
			if (modelRef) {
				localStorage.setItem(modelStorageKey, modelRef);
			} else {
				localStorage.removeItem(modelStorageKey);
			}
		} catch {
			// Ignore storage errors.
		}
	}, [currentModelRef, modelStorageKey, selectedModelRef]);

	const displayError = commandError ?? error;
	const showSkeleton = messages.length === 0 && !displayError && historyLoading;
	const showTimelineTreePreview =
		typeof window !== "undefined" &&
		window.localStorage.getItem("oqto:timeline-tree-preview") === "1";

	const ChatSkeleton = (
		<div className="flex-1 flex flex-col gap-4 min-h-0 animate-pulse">
			<div className="flex-1 bg-muted/20 p-4 space-y-6">
				<div className="mr-8 space-y-2">
					<div className="h-4 bg-muted/40 w-24" />
					<div className="h-16 bg-muted/30" />
				</div>
				<div className="ml-8 space-y-2">
					<div className="h-4 bg-muted/40 w-16 ml-auto" />
					<div className="h-10 bg-muted/30" />
				</div>
				<div className="mr-8 space-y-2">
					<div className="h-4 bg-muted/40 w-24" />
					<div className="h-24 bg-muted/30" />
				</div>
			</div>
			<div className="h-10 bg-muted/20" />
		</div>
	);
	// Slash query stored in ref -- updated synchronously in handleInputChange
	const slashQueryRef = useRef(parseSlashInput(inputValueRef.current));

	const enqueueMessage = useCallback(
		(rawText?: string) => {
			const trimmed = (rawText ?? inputValueRef.current).trim();
			if (!trimmed) return;

			if (fileAttachments.length > 0) {
				toast.error("Queued messages do not support file attachments yet.");
				return;
			}

			if (draftSaveTimeoutRef.current) {
				clearTimeout(draftSaveTimeoutRef.current);
				draftSaveTimeoutRef.current = null;
			}

			const isShellCommand = trimmed.startsWith("!");
			const shellCommand = isShellCommand ? trimmed.slice(1).trim() : "";
			let message = trimmed;
			if (isShellCommand && shellCommand) {
				message = `Run this shell command and show me the output:\n\`\`\`bash\n${shellCommand}\n\`\`\``;
			}

			const id =
				typeof crypto !== "undefined" && "randomUUID" in crypto
					? crypto.randomUUID()
					: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

			setQueuedMessages((prev) => [...prev, { id, text: message }]);
			setInput("");
			setFileAttachments([]);
			setShowSlashPopup(false);
			setCommandError(null);
			try {
				localStorage.removeItem(draftStorageKey);
			} catch {
				// Ignore localStorage errors
			}
			if (inputRef.current) {
				inputRef.current.style.height = "auto";
			}
		},
		[draftStorageKey, fileAttachments.length, setInput],
	);
	const builtInCommands = useMemo<SlashCommand[]>(() => {
		const commands: SlashCommand[] = [
			{ name: "compact", description: "Summarize context" },
			{ name: "new", description: "Start a fresh session" },
			{ name: "reset", description: "Reload personality and user files" },
			{ name: "abort", description: "Abort current run" },
			{ name: "stats", description: "Show session stats" },
			{ name: "steer", description: "Send a steering message" },
			{ name: "followup", description: "Queue a follow-up message" },
		];
		if (canSwitchModel) {
			commands.push({
				name: "model",
				description: "Switch model (provider/model)",
			});
		}
		return commands;
	}, [canSwitchModel]);
	const builtInCommandNames = useMemo(
		() => new Set(builtInCommands.map((cmd) => cmd.name)),
		[builtInCommands],
	);
	const slashCommands = useMemo<SlashCommand[]>(() => {
		const merged = [...builtInCommands];
		const seen = new Set(merged.map((cmd) => cmd.name));
		for (const cmd of customCommands) {
			if (!seen.has(cmd.name)) {
				merged.push(cmd);
				seen.add(cmd.name);
			}
		}
		return merged;
	}, [builtInCommands, customCommands]);
	const filteredModels = useMemo(() => {
		const query = modelQuery.trim();
		if (!query) return availableModels;
		return availableModels.filter((model) => {
			const fullRef = `${model.provider}/${model.id}`;
			return (
				fuzzyMatch(query, fullRef) ||
				fuzzyMatch(query, model.provider) ||
				fuzzyMatch(query, model.id) ||
				(model.name ? fuzzyMatch(query, model.name) : false)
			);
		});
	}, [availableModels, modelQuery]);
	// Calculate current context window size from message content.
	// Pi's usage fields are cumulative session totals, not current context.
	// ── Pi session stats for context gauge ──
	// Fetched once on session load, then updated from stream.message_end usage.
	const [piSessionTokens, setPiSessionTokens] = useState<{
		input: number;
		output: number;
	} | null>(null);
	const [piContextWindowLength, setPiContextWindowLength] = useState<
		number | null
	>(null);

	// Fetch Pi session stats when the active session changes
	useEffect(() => {
		setPiSessionTokens(null);
		setPiContextWindowLength(null);
		if (!selectedSessionId) {
			return;
		}
		let cancelled = false;
		const fetchStats = async () => {
			try {
				const stats =
					await getWsManager().agentGetSessionStats(selectedSessionId);
				if (cancelled) return;
				const parsed = parsePiSessionStats(stats);
				setPiContextWindowLength(
					parsed.contextWindowLength > 0 ? parsed.contextWindowLength : null,
				);
				setPiSessionTokens(
					parsed.input > 0 || parsed.output > 0
						? { input: parsed.input, output: parsed.output }
						: null,
				);
			} catch {
				if (!cancelled) {
					// Stats unavailable (session not running in Pi) - that's fine
					setPiSessionTokens(null);
					setPiContextWindowLength(null);
				}
			}
		};
		void fetchStats();
		return () => {
			cancelled = true;
		};
	}, [selectedSessionId]);

	// Refresh stats after compaction completes (context window changes significantly)
	const lastCompactionText = useMemo(() => {
		for (let i = messages.length - 1; i >= 0; i--) {
			for (const part of messages[i].parts) {
				if (
					part.type === "compaction" &&
					"text" in part &&
					(part as { text: string }).text !== "Compacting context..."
				) {
					return (part as { text: string }).text;
				}
			}
		}
		return null;
	}, [messages]);

	useEffect(() => {
		if (!lastCompactionText || !selectedSessionId) return;
		let cancelled = false;
		const refreshStats = async () => {
			try {
				const stats =
					await getWsManager().agentGetSessionStats(selectedSessionId);
				if (cancelled) return;
				const parsed = parsePiSessionStats(stats);
				setPiContextWindowLength(
					parsed.contextWindowLength > 0 ? parsed.contextWindowLength : null,
				);
				if (parsed.input > 0 || parsed.output > 0) {
					setPiSessionTokens({ input: parsed.input, output: parsed.output });
				}
			} catch {
				// Stats unavailable
			}
		};
		void refreshStats();
		return () => {
			cancelled = true;
		};
	}, [lastCompactionText, selectedSessionId]);

	const contextTokenCount = useMemo(() => {
		if (messages.length === 0) {
			return { inputTokens: 0, outputTokens: 0 };
		}

		// Priority 1: Real usage from the last assistant message (set during streaming)
		for (let i = messages.length - 1; i >= 0; i--) {
			const msg = messages[i];
			if (msg.role === "assistant" && msg.usage) {
				const u = msg.usage;
				const input = normalizeTokenCount(u.input_tokens);
				const output = normalizeTokenCount(u.output_tokens);
				if (input > 0 || output > 0) {
					return { inputTokens: input, outputTokens: output };
				}
			}
		}

		// Priority 2: Pi session token totals (cumulative session stats)
		if (
			piSessionTokens &&
			(piSessionTokens.input > 0 || piSessionTokens.output > 0)
		) {
			return {
				inputTokens: piSessionTokens.input,
				outputTokens: piSessionTokens.output,
			};
		}

		// Priority 3: Pi-reported context window length (fallback estimate)
		// Note: contextWindowLength is the current window size, not cumulative
		if (piContextWindowLength && piContextWindowLength > 0) {
			return { inputTokens: piContextWindowLength, outputTokens: 0 };
		}

		// Priority 4: Fallback estimate from text content (4 chars ~ 1 token)
		let lastCompactionIndex = -1;
		for (let i = messages.length - 1; i >= 0; i--) {
			if (messages[i].parts.some((p) => p.type === "compaction")) {
				lastCompactionIndex = i;
				break;
			}
		}

		let inputTokens = 0;
		let outputTokens = 0;
		const startIndex = lastCompactionIndex >= 0 ? lastCompactionIndex + 1 : 0;

		for (let i = startIndex; i < messages.length; i++) {
			const msg = messages[i];
			for (const part of msg.parts) {
				const text =
					("text" in part ? (part as { text?: string }).text : null) ??
					("tool_input" in part
						? (part as { tool_input?: string }).tool_input
						: null) ??
					("output" in part ? (part as { output?: string }).output : null) ??
					"";
				if (text) {
					const estimatedTokens = Math.ceil(text.length / 4);
					if (msg.role === "user") {
						inputTokens += estimatedTokens;
					} else {
						outputTokens += estimatedTokens;
					}
				}
			}
		}
		return { inputTokens, outputTokens };
	}, [messages, piContextWindowLength, piSessionTokens]);

	const gaugeTokens = contextTokenCount;

	// Report token usage to parent when it changes
	useEffect(() => {
		if (onTokenUsageChange) {
			onTokenUsageChange({
				inputTokens: gaugeTokens.inputTokens,
				outputTokens: gaugeTokens.outputTokens,
				maxTokens: contextWindowLimit,
			});
		}
	}, [gaugeTokens, contextWindowLimit, onTokenUsageChange]);

	// Dictation hook
	const dictation = useDictation({
		config: voiceConfig,
		onTranscript: useCallback(
			(text: string) => {
				const prev = inputValueRef.current;
				setInput(prev ? `${prev} ${text}` : text);
			},
			[setInput],
		),
		vadTimeoutMs: features?.voice?.vad_timeout_ms,
		autoSendOnFinal: true,
		autoSendDelayMs: 50,
		onAutoSend: () => {
			const sendBtn = document.querySelector(
				"[data-dictation-send]",
			) as HTMLButtonElement | null;
			sendBtn?.click();
		},
	});

	useEffect(() => {
		if (selectedModelRef || !currentModelRef) return;
		setSelectedModelRef(currentModelRef);
	}, [currentModelRef, selectedModelRef]);

	useEffect(() => {
		// Only fetch models once session is active (piState available)
		if (!isConnected || !piState) return;
		const targetSessionId = selectedSessionId ?? piState.sessionId ?? null;
		if (!targetSessionId) return;
		let active = true;
		getWsManager()
			.agentGetAvailableModels(targetSessionId)
			.then((result) => {
				if (active) setAvailableModels((result as PiModelInfo[]) ?? []);
			})
			.catch(() => {
				if (active) setAvailableModels([]);
			});
		return () => {
			active = false;
		};
	}, [isConnected, piState, selectedSessionId]);

	useEffect(() => {
		// Only fetch commands once session is active (piState available)
		if (!isConnected || !piState) return;
		const targetSessionId = selectedSessionId ?? piState.sessionId ?? null;
		if (!targetSessionId) return;
		let active = true;
		const manager = getWsManager();
		manager
			.agentGetCommands(targetSessionId)
			.then((commands) => {
				if (!active) return;
				setCustomCommands(
					commands.map((cmd) => ({
						name: cmd.name,
						description: cmd.description ?? undefined,
					})),
				);
			})
			.catch(() => {
				if (active) setCustomCommands([]);
			});
		return () => {
			active = false;
		};
	}, [isConnected, piState, selectedSessionId]);

	// biome-ignore lint/correctness/useExhaustiveDependencies: contextWindowLimit is stable
	const refreshStats = useCallback(async () => {
		const targetSessionId = selectedSessionId ?? piState?.sessionId ?? null;
		if (!targetSessionId) return;
		try {
			const stats = await getWsManager().agentGetSessionStats(targetSessionId);
			console.log("[Pi stats] raw:", stats);
			const fallbackStats = sessionMeta?.stats ?? null;
			const tokens =
				stats && typeof stats === "object" && "tokens" in stats
					? (stats as { tokens?: { input?: number; output?: number } }).tokens
					: fallbackStats
						? {
								input: fallbackStats.tokens_in,
								output: fallbackStats.tokens_out,
							}
						: null;
			if (tokens) {
				console.log(
					"[Pi stats] tokens:",
					tokens,
					"contextWindow:",
					contextWindowLimit,
				);
				setSessionTokens({
					input: tokens.input ?? 0,
					output: tokens.output ?? 0,
				});
			}
		} catch {
			// Ignore stats errors
		}
	}, [piState?.sessionId, selectedSessionId, sessionMeta?.stats]);

	// biome-ignore lint/correctness/useExhaustiveDependencies: messages.length triggers refresh when message count changes
	useEffect(() => {
		if (!isConnected || isStreaming) return;
		// Small delay to ensure Pi has updated internal stats after streaming
		const timer = setTimeout(() => refreshStats(), 300);
		return () => clearTimeout(timer);
	}, [isConnected, isStreaming, messages.length, refreshStats]);

	// Discrete sessions: reset scroll state only when switching to a different session.
	const prevSessionIdRef = useRef(selectedSessionId);
	useEffect(() => {
		if (!selectedSessionId) return;
		if (selectedSessionId === prevSessionIdRef.current) return;
		prevSessionIdRef.current = selectedSessionId;
		setIsUserScrolled(false);
		isUserScrolledRef.current = false;
	}, [selectedSessionId]);

	// Scroll to message when scrollToMessageId changes (from search results)
	useEffect(() => {
		if (!scrollToMessageId || !messagesContainerRef.current) return;

		let targetId = scrollToMessageId;
		if (targetId.startsWith("line-")) {
			const idx = Number.parseInt(targetId.slice(5), 10);
			const resolved = Number.isFinite(idx) ? messages[idx - 1]?.id : undefined;
			if (resolved) targetId = resolved;
		}

		// Find the message element with this ID
		const messageEl = messagesContainerRef.current.querySelector(
			`[data-message-id="${targetId}"]`,
		);

		if (messageEl) {
			// Ensure we have enough messages visible
			const messageIndex = messages.findIndex((m) => m.id === targetId);
			if (messageIndex !== -1) {
				const messagesFromEnd = messages.length - messageIndex;
				if (messagesFromEnd > visibleCount) {
					setVisibleCount(messagesFromEnd + 10);
				}
			}

			// Scroll to the message
			requestAnimationFrame(() => {
				programmaticScrollRef.current = true;
				messageEl.scrollIntoView({ behavior: "smooth", block: "center" });
				// Add highlight animation
				messageEl.classList.add("search-highlight");
				setTimeout(() => {
					messageEl.classList.remove("search-highlight");
				}, 2000);
			});

			setIsUserScrolled(true);
			onScrollToMessageComplete?.();
		}
	}, [scrollToMessageId, messages, visibleCount, onScrollToMessageComplete]);

	// Keep ref mirror in sync with state
	useEffect(() => {
		isUserScrolledRef.current = isUserScrolled;
	}, [isUserScrolled]);

	// Preserve viewport position across authoritative message replacement.
	// This keeps agent_end sync visually stable when the message list is
	// reconciled to durable history.
	useLayoutEffect(() => {
		void messages;
		const container = messagesContainerRef.current;
		if (!container || !initialScrollDoneRef.current) return;

		// Never compensate during active streaming. That can fight with user
		// wheel/touch scrolling and produce visible twitching.
		if (!isStreaming && !isAwaitingResponse) {
			const prevTop = lastScrollTopRef.current;
			const prevHeight = lastScrollHeightRef.current;
			if (prevTop !== null && prevHeight !== null) {
				const wasNearBottom =
					prevHeight - prevTop - container.clientHeight < 80;
				if (isUserScrolledRef.current || !wasNearBottom) {
					const delta = container.scrollHeight - prevHeight;
					if (delta !== 0) {
						programmaticScrollRef.current = true;
						container.scrollTop = prevTop + delta;
					}
				}
			}
		}

		lastScrollTopRef.current = container.scrollTop;
		lastScrollHeightRef.current = container.scrollHeight;
	}, [isAwaitingResponse, isStreaming, messages]);

	// Auto-scroll when messages change (new message, streaming token update,
	// tool call result). Only scrolls if user hasn't manually scrolled up.
	// biome-ignore lint/correctness/useExhaustiveDependencies: setBusyForEvent is stable callback
	useEffect(() => {
		if (!initialScrollDoneRef.current) return;
		if (!isUserScrolledRef.current) {
			scrollToBottom();
		}
	}, [messages, scrollToBottom]);

	// Strict bottom lock during active streaming while user is not scrolling.
	// This runs in layout phase so the bottom edge remains visually fixed.
	useLayoutEffect(() => {
		void messages.length;
		if (!initialScrollDoneRef.current) return;
		if (isUserScrolledRef.current) return;
		if (!(isStreaming || isAwaitingResponse || sendPending)) return;
		const container = messagesContainerRef.current;
		if (!container) return;
		const targetTop = Math.max(
			0,
			container.scrollHeight - container.clientHeight,
		);
		if (Math.abs(container.scrollTop - targetTop) < 1) return;
		programmaticScrollRef.current = true;
		container.scrollTop = targetTop;
		lastScrollTopRef.current = container.scrollTop;
		lastScrollHeightRef.current = container.scrollHeight;
	}, [messages.length, isStreaming, isAwaitingResponse, sendPending]);

	// Update isUserScrolled from real user scroll events only.
	// wheel/touch/pointer events on the container set userInitiatedScrollRef
	// so we know the following scroll event came from the user.
	useEffect(() => {
		const container = messagesContainerRef.current;
		if (!container) return;
		const mark = () => {
			userInitiatedScrollRef.current = true;
			// Only mark as scrolled-away if we are NOT already at the bottom.
			// This prevents the jump-to-bottom button from flashing when the
			// user scrolls down and reaches the end of the chat.
			const atBottom =
				container.scrollHeight - container.scrollTop - container.clientHeight <
				80;
			if (!atBottom) {
				setIsUserScrolled(true);
				isUserScrolledRef.current = true;
			}
		};
		container.addEventListener("wheel", mark, { passive: true });
		container.addEventListener("touchmove", mark, { passive: true });
		container.addEventListener("pointerdown", mark, { passive: true });
		container.addEventListener("mousedown", mark, { passive: true });
		return () => {
			container.removeEventListener("wheel", mark);
			container.removeEventListener("touchmove", mark);
			container.removeEventListener("pointerdown", mark);
			container.removeEventListener("mousedown", mark);
		};
	}, []);

	const handleScrollToBottom = useCallback(() => {
		userInitiatedScrollRef.current = false;
		setIsUserScrolled(false);
		isUserScrolledRef.current = false;
		setCachedScrollPosition(null, scrollStorageKey);
		scrollToBottom();
	}, [scrollStorageKey, scrollToBottom]);

	// Initial scroll position
	useLayoutEffect(() => {
		if (initialScrollDoneRef.current || !messagesContainerRef.current) return;
		if (messages.length === 0) return;
		initialScrollDoneRef.current = true;
		const container = messagesContainerRef.current;
		const cachedPosition = getCachedScrollPosition(scrollStorageKey);
		if (cachedPosition !== null) {
			programmaticScrollRef.current = true;
			container.scrollTop = cachedPosition;
		} else {
			programmaticScrollRef.current = true;
			messagesEndRef.current?.scrollIntoView();
		}
		lastScrollTopRef.current = container.scrollTop;
		lastScrollHeightRef.current = container.scrollHeight;
	}, [messages.length, scrollStorageKey]);

	const handleScroll = useCallback(() => {
		const container = messagesContainerRef.current;
		if (!container) return;

		// Load more when near top
		if (container.scrollTop < 100 && visibleCount < messages.length) {
			const prevScrollHeight = container.scrollHeight;
			setVisibleCount((prev) => nextVisibleMessageCount(prev, messages.length));
			requestAnimationFrame(() => {
				programmaticScrollRef.current = true;
				container.scrollTop = container.scrollHeight - prevScrollHeight;
			});
		}

		// Ignore scroll events caused by programmatic updates.
		if (programmaticScrollRef.current) {
			programmaticScrollRef.current = false;
			userInitiatedScrollRef.current = false;
			return;
		}

		const atBottom =
			container.scrollHeight - container.scrollTop - container.clientHeight <
			80;

		// Never mark as "user scrolled up" unless we observed an explicit user
		// gesture. This avoids false positives from streaming/layout growth.
		if (!userInitiatedScrollRef.current) {
			if (atBottom) {
				setIsUserScrolled(false);
				isUserScrolledRef.current = false;
				setCachedScrollPosition(null, scrollStorageKey);
			}
			return;
		}

		userInitiatedScrollRef.current = false;
		setIsUserScrolled(!atBottom);
		isUserScrolledRef.current = !atBottom;
		if (atBottom) {
			setCachedScrollPosition(null, scrollStorageKey);
		} else {
			setCachedScrollPosition(container.scrollTop, scrollStorageKey);
		}
		lastScrollTopRef.current = container.scrollTop;
		lastScrollHeightRef.current = container.scrollHeight;
	}, [scrollStorageKey, visibleCount, messages.length]);

	// Focus input on mount - only on desktop to avoid opening keyboard on mobile
	useEffect(() => {
		// Check if device has a coarse pointer (touch) - indicates mobile
		const isTouchDevice = window.matchMedia("(pointer: coarse)").matches;
		if (!isTouchDevice) {
			inputRef.current?.focus();
		}
	}, []);

	// Auto-resize is now handled inline in handleInputChange for better performance.
	// This effect only handles dictation mode changes.
	useEffect(() => {
		if (dictation.isActive && inputRef.current) {
			inputRef.current.style.height = "36px";
		}
	}, [dictation.isActive]);

	// Handle file upload
	const handleFileUpload = useCallback(
		async (files: FileList | null) => {
			if (!files || files.length === 0) return;

			// File attachments require a workspace path to upload to
			// The path is always available for default chat, but may be loading initially
			if (!normalizedWorkspacePath) {
				toast.error(
					"Workspace path is still loading. Please try again in a moment.",
				);
				return;
			}

			setIsUploading(true);

			try {
				for (const file of Array.from(files)) {
					try {
						if (!normalizedWorkspacePath) {
							throw new Error("Workspace path is still loading");
						}
						const uploadPath = `uploads/${file.name}`;
						await uploadFileMux(normalizedWorkspacePath, uploadPath, file);

						const attachment: FileAttachment = {
							id: `file-${Date.now()}-${Math.random().toString(36).slice(2)}`,
							path: uploadPath,
							filename: file.name,
							type: "file",
						};
						setFileAttachments((prev) => [...prev, attachment]);
					} catch (err) {
						console.error("Failed to upload file:", err);
						toast.error(`Failed to upload ${file.name}`, {
							description: err instanceof Error ? err.message : "Unknown error",
						});
					}
				}
			} finally {
				setIsUploading(false);
				if (fileInputRef.current) {
					fileInputRef.current.value = "";
				}
			}
		},
		[normalizedWorkspacePath],
	);

	const handleModelChange = useCallback(
		async (value: string) => {
			if (!canSwitchModel) {
				throw new Error("Model switching is only available when Pi is idle.");
			}
			const separatorIndex = value.indexOf("/");
			if (separatorIndex <= 0 || separatorIndex === value.length - 1) return;
			const provider = value.slice(0, separatorIndex);
			const modelId = value.slice(separatorIndex + 1);
			const previousModelRef = selectedModelRef;
			setSelectedModelRef(value);
			setIsSwitchingModel(true);
			try {
				const targetSessionId = selectedSessionId ?? piState?.sessionId ?? null;
				if (!targetSessionId) {
					throw new Error("No active session");
				}
				// Use WebSocket to set model - works for both default chat and workspace
				const manager = getWsManager();
				await manager.agentSetModel(targetSessionId, provider, modelId);
				await refresh();
			} catch (err) {
				console.error("Failed to switch model:", err);
				// Revert optimistic update on failure
				setSelectedModelRef(previousModelRef);
			} finally {
				setIsSwitchingModel(false);
			}
		},
		[
			canSwitchModel,
			piState?.sessionId,
			refresh,
			selectedModelRef,
			selectedSessionId,
		],
	);

	// biome-ignore lint/correctness/useExhaustiveDependencies: messages dep intentionally omitted
	const runSlashCommand = useCallback(
		async (command: string, args: string) => {
			setCommandError(null);
			const trimmedArgs = args.trim();
			const needsArgs = ["steer", "followup", "model"].includes(command);
			if (needsArgs && !trimmedArgs) {
				setInput(`/${command} `);
				inputRef.current?.focus();
				return { handled: true, clearInput: false };
			}

			switch (command) {
				case "compact": {
					await compact(trimmedArgs || undefined);
					await refresh();
					return { handled: true, clearInput: true };
				}
				case "new": {
					await newSession();
					return { handled: true, clearInput: true };
				}
				case "reset": {
					await resetSession();
					return { handled: true, clearInput: true };
				}
				case "abort": {
					await abort();
					return { handled: true, clearInput: true };
				}
				case "stats": {
					const targetSessionId =
						selectedSessionId ?? piState?.sessionId ?? null;
					if (!targetSessionId) {
						throw new Error("No active session");
					}
					const stats =
						await getWsManager().agentGetSessionStats(targetSessionId);
					const safeStats = stats && typeof stats === "object" ? stats : null;
					const fallbackStats = sessionMeta?.stats ?? null;
					const tokens =
						safeStats && "tokens" in safeStats
							? (
									safeStats as {
										tokens?: {
											input?: number;
											output?: number;
											cache_read?: number;
											cache_write?: number;
											total?: number;
										};
									}
								).tokens
							: fallbackStats
								? {
										input: fallbackStats.tokens_in,
										output: fallbackStats.tokens_out,
										cache_read: fallbackStats.cache_read,
										cache_write: fallbackStats.cache_write,
										total:
											fallbackStats.tokens_in +
											fallbackStats.tokens_out +
											fallbackStats.cache_read +
											fallbackStats.cache_write,
									}
								: null;
					const text = [
						"Session stats",
						`- user_messages: ${
							typeof (safeStats as { user_messages?: number })
								?.user_messages === "number"
								? (safeStats as { user_messages?: number }).user_messages
								: 0
						}`,
						`- assistant_messages: ${
							typeof (safeStats as { assistant_messages?: number })
								?.assistant_messages === "number"
								? (safeStats as { assistant_messages?: number })
										.assistant_messages
								: 0
						}`,
						`- tool_calls: ${
							typeof (safeStats as { tool_calls?: number })?.tool_calls ===
							"number"
								? (safeStats as { tool_calls?: number }).tool_calls
								: 0
						}`,
						`- total_messages: ${
							typeof (safeStats as { total_messages?: number })
								?.total_messages === "number"
								? (safeStats as { total_messages?: number }).total_messages
								: 0
						}`,
						tokens
							? `- tokens: in ${tokens.input ?? 0}, out ${
									tokens.output ?? 0
								}, cache read ${tokens.cache_read ?? 0}, cache write ${
									tokens.cache_write ?? 0
								}, total ${tokens.total ?? 0}`
							: "- tokens: 0",
					].join("\n");
					appendLocalAssistantMessage(text);
					return { handled: true, clearInput: true };
				}
				case "steer": {
					await send(trimmedArgs, { mode: "steer" });
					return { handled: true, clearInput: true };
				}
				case "followup": {
					enqueueMessage(trimmedArgs);
					return { handled: true, clearInput: true };
				}
				case "model": {
					if (!canSwitchModel) {
						throw new Error(
							"Model switching is only available when Pi is idle.",
						);
					}
					const separatorIndex = trimmedArgs.indexOf("/");
					if (
						separatorIndex <= 0 ||
						separatorIndex === trimmedArgs.length - 1
					) {
						throw new Error("Model must be provider/model");
					}
					await handleModelChange(trimmedArgs);
					return { handled: true, clearInput: true };
				}
				default:
					return { handled: false, clearInput: false };
			}
		},
		[
			abort,
			appendLocalAssistantMessage,
			canSwitchModel,
			compact,
			enqueueMessage,
			handleModelChange,
			newSession,
			piState?.sessionId,
			refresh,
			resetSession,
			selectedSessionId,
			send,
			sessionMeta?.stats,
		],
	);

	const handleSend = useCallback(
		async (mode: "prompt" | "steer" | "follow_up" = "steer") => {
			const trimmed = inputValueRef.current.trim();
			if (!trimmed && fileAttachments.length === 0) return;

			const sq = slashQueryRef.current;
			if (sq.isSlash && builtInCommandNames.has(sq.command)) {
				try {
					const result = await runSlashCommand(sq.command, sq.args);
					if (result.handled) {
						if (result.clearInput) {
							setInput("");
							setFileAttachments([]);
							if (inputRef.current) {
								inputRef.current.style.height = "auto";
							}
						}
						setShowSlashPopup(false);
						return;
					}
				} catch (err) {
					setCommandError(
						err instanceof Error ? err : new Error("Command failed"),
					);
					return;
				}
			}

			if (draftSaveTimeoutRef.current) {
				clearTimeout(draftSaveTimeoutRef.current);
				draftSaveTimeoutRef.current = null;
			}

			// Check for shell command (starts with "!")
			const isShellCommand = trimmed.startsWith("!");
			const shellCommand = isShellCommand ? trimmed.slice(1).trim() : "";

			// Build message with file attachments
			let message = trimmed;
			if (isShellCommand && shellCommand) {
				// Convert shell command to a prompt for Pi's bash tool
				message = `Run this shell command and show me the output:\n\`\`\`bash\n${shellCommand}\n\`\`\``;
			} else if (fileAttachments.length > 0) {
				const fileRefs = fileAttachments.map((f) => `@${f.path}`).join(" ");
				message = `${fileRefs}\n\n${trimmed}`;
			}

			const draftInput = inputValueRef.current;
			const draftAttachments = fileAttachments;
			const hasHistory =
				messages.length > 0 || (piState?.messageCount ?? 0) > 0;
			const effectiveMode =
				mode === "follow_up" || mode === "steer"
					? hasHistory
						? mode
						: "prompt"
					: mode;

			setSendPending(true);
			const resolvedSessionId = selectedSessionId ?? null;
			if (!resolvedSessionId) {
				setSendPending(false);
				toast.error("No active chat session.");
				return;
			}

			setInput("");
			setFileAttachments([]);
			// Clear draft from localStorage
			try {
				localStorage.removeItem(draftStorageKey);
			} catch {
				// Ignore localStorage errors
			}
			// Reset textarea height
			if (inputRef.current) {
				inputRef.current.style.height = "auto";
			}

			userInitiatedScrollRef.current = false;
			setIsUserScrolled(false);
			isUserScrolledRef.current = false;

			setSendPendingSessionId(resolvedSessionId);
			try {
				await send(message, {
					mode: effectiveMode,
					sessionId: resolvedSessionId,
				});
				// Notify that a message was sent (for sidebar refresh)
				onMessageSent?.();
			} catch {
				setSendPending(false);
				setSendPendingSessionId(null);
				setInput(draftInput);
				setFileAttachments(draftAttachments);
				toast.error("Failed to send message.");
			}
		},
		[
			builtInCommandNames,
			draftStorageKey,
			fileAttachments,
			messages.length,
			onMessageSent,
			piState?.messageCount,
			runSlashCommand,
			selectedSessionId,
			send,
			setInput,
		],
	);

	const handleQueueIntent = useCallback(() => {
		const sq = slashQueryRef.current;
		if (sq.isSlash && builtInCommandNames.has(sq.command)) {
			handleSend("steer");
			return;
		}
		enqueueMessage();
	}, [builtInCommandNames, enqueueMessage, handleSend]);

	const messagesRef = useRef(messages);
	messagesRef.current = messages;
	const piStateRef = useRef(piState);
	piStateRef.current = piState;
	useEffect(() => {
		if (queuedMessages.length === 0) return;
		if (isStreaming || isAwaitingResponse) return;
		if (queueSendInFlightRef.current) return;

		const now = Date.now();
		if (queueCooldownRef.current && now - queueCooldownRef.current < 2000) {
			return;
		}

		const next = queuedMessages[0];
		if (!next?.text) return;

		queueSendInFlightRef.current = true;
		(async () => {
			setSendPending(true);
			const resolvedSessionId = selectedSessionId ?? null;
			if (!resolvedSessionId) {
				setSendPending(false);
				toast.error("No active chat session.");
				return;
			}
			setSendPendingSessionId(resolvedSessionId);
			const hasHistory =
				messagesRef.current.length > 0 ||
				(piStateRef.current?.messageCount ?? 0) > 0;
			const queueMode = hasHistory ? "follow_up" : "prompt";
			send(next.text, { mode: queueMode, sessionId: resolvedSessionId })
				.then(() => {
					setQueuedMessages((prev) => prev.slice(1));
					onMessageSent?.();
				})
				.catch(() => {
					queueCooldownRef.current = Date.now();
					setSendPending(false);
					setSendPendingSessionId(null);
					toast.error("Failed to send queued message.");
				})
				.finally(() => {
					queueSendInFlightRef.current = false;
				});
		})().catch(() => {
			queueSendInFlightRef.current = false;
			setSendPending(false);
			setSendPendingSessionId(null);
			toast.error("Failed to send queued message.");
		});
	}, [
		isAwaitingResponse,
		isStreaming,
		onMessageSent,
		queuedMessages,
		selectedSessionId,
		send,
	]);

	const handleQueueEdit = useCallback((id: string, text: string) => {
		setQueuedMessages((prev) =>
			prev.map((item) => (item.id === id ? { ...item, text } : item)),
		);
	}, []);

	const handleQueueRemove = useCallback((id: string) => {
		setQueuedMessages((prev) => prev.filter((item) => item.id !== id));
	}, []);

	const handleQueueMove = useCallback((id: string, direction: -1 | 1) => {
		setQueuedMessages((prev) => {
			const index = prev.findIndex((item) => item.id === id);
			if (index < 0) return prev;
			const targetIndex = index + direction;
			if (targetIndex < 0 || targetIndex >= prev.length) return prev;
			const next = [...prev];
			const [item] = next.splice(index, 1);
			next.splice(targetIndex, 0, item);
			return next;
		});
	}, []);

	const handleQueueClear = useCallback(() => {
		setQueuedMessages([]);
	}, []);

	const handleKeyDown = useCallback(
		(e: KeyboardEvent<HTMLTextAreaElement>) => {
			const sq = slashQueryRef.current;
			if (showSlashPopup && sq.isSlash && !sq.args) {
				if (
					["ArrowDown", "ArrowUp", "Enter", "Tab", "Escape"].includes(e.key)
				) {
					return;
				}
			}
			// Let file mention popup handle its keys
			if (showFileMentionPopup) {
				if (
					["ArrowDown", "ArrowUp", "Enter", "Tab", "Escape"].includes(e.key)
				) {
					return;
				}
			}
			if (e.key === "Enter" && !e.shiftKey) {
				e.preventDefault();
				// Prompt on Enter, queue on Ctrl/Cmd+Enter
				if (e.ctrlKey || e.metaKey) {
					handleQueueIntent();
				} else {
					handleSend("prompt");
				}
			}
			if (e.key === "Escape") {
				setShowFileMentionPopup(false);
				setShowSlashPopup(false);
			}
		},
		[handleQueueIntent, handleSend, showFileMentionPopup, showSlashPopup],
	);

	const handleInputChange = useCallback(
		(e: ChangeEvent<HTMLTextAreaElement>) => {
			const textarea = e.target;
			const value = textarea.value;

			// Update ref and slash query synchronously -- no React renders
			inputValueRef.current = value;
			slashQueryRef.current = parseSlashInput(value);
			setCommandError(null);

			// Keep textarea stable during dictation to avoid reflow storms.
			if (dictation.isActive) {
				textarea.style.height = "36px";
			} else {
				// Auto-resize textarea immediately
				textarea.style.height = "auto";
				textarea.style.height = `${Math.min(textarea.scrollHeight, 200)}px`;
			}

			// Debounce draft persistence to localStorage (300ms)
			if (draftSaveTimeoutRef.current) {
				clearTimeout(draftSaveTimeoutRef.current);
			}
			draftSaveTimeoutRef.current = setTimeout(() => {
				try {
					if (value.trim()) {
						localStorage.setItem(draftStorageKey, value);
					} else {
						localStorage.removeItem(draftStorageKey);
					}
				} catch {
					// Ignore localStorage errors
				}
			}, 300);

			// Defer all React state updates to avoid blocking typing
			requestAnimationFrame(() => {
				startTransition(() => {
					setCanSendInput(!!value.trim());

					if (value.startsWith("/")) {
						setShowSlashPopup(true);
						setShowFileMentionPopup(false);
						setFileMentionQuery("");
						return;
					}

					setShowSlashPopup(false);

					// Show file mention popup when typing @
					const atMatch = value.match(/@[^\s]*$/);
					if (atMatch) {
						setShowFileMentionPopup(true);
						setFileMentionQuery(atMatch[1]);
					} else {
						setShowFileMentionPopup(false);
						setFileMentionQuery("");
					}
				});
			});
		},
		[draftStorageKey, dictation.isActive],
	);

	const longPressTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
	const suppressClickRef = useRef(false);

	const clearLongPress = useCallback(() => {
		if (longPressTimerRef.current) {
			clearTimeout(longPressTimerRef.current);
			longPressTimerRef.current = null;
		}
	}, []);

	const handleSendClick = useCallback(() => {
		if (suppressClickRef.current) {
			suppressClickRef.current = false;
			return;
		}
		handleSend("prompt");
	}, [handleSend]);

	const handleSendPointerDown = useCallback(
		(e: React.PointerEvent<HTMLButtonElement>) => {
			if (e.pointerType !== "touch") return;
			clearLongPress();
			longPressTimerRef.current = setTimeout(() => {
				suppressClickRef.current = true;
				handleQueueIntent();
			}, 450);
		},
		[clearLongPress, handleQueueIntent],
	);

	const handleSendPointerUp = useCallback(() => {
		clearLongPress();
	}, [clearLongPress]);

	const handleSendPointerLeave = useCallback(() => {
		clearLongPress();
	}, [clearLongPress]);

	const handleFileSelect = useCallback(
		(file: FileAttachment) => {
			setFileAttachments((prev) => [...prev, file]);
			// Remove the @query from input
			const newValue = inputValueRef.current.replace(/@[^\s]*$/, "");
			setInput(newValue);
			setShowFileMentionPopup(false);
			setFileMentionQuery("");
			inputRef.current?.focus();
		},
		[setInput],
	);

	// Insert an `@<path>` mention at the cursor in the live composer.
	const insertFileMentionAtCursor = useCallback(
		(path: string) => {
			const textarea = inputRef.current;
			const currentValue = inputValueRef.current;
			const cursor = textarea?.selectionStart ?? currentValue.length;
			const { value: nextValue, cursor: nextCursor } = insertFileMention(
				currentValue,
				cursor,
				path,
			);
			setInput(nextValue);
			requestAnimationFrame(() => {
				const el = inputRef.current;
				if (!el) return;
				el.focus();
				el.setSelectionRange(nextCursor, nextCursor);
			});
		},
		[setInput],
	);

	// File-tree "Mention file in chat" action emits oqto:mention-file-in-chat;
	// handle it in the live composer (previously only wired in the unrendered
	// ChatInputArea, so the action did nothing). oqto-drwc.
	// useeffect-guardrail: allow - window CustomEvent subscription for file-tree @mention insertion
	useEffect(() => {
		const onMentionFile = (event: Event) => {
			const detail = (event as CustomEvent<{ path?: string }>).detail;
			if (detail?.path) insertFileMentionAtCursor(detail.path);
		};
		window.addEventListener("oqto:mention-file-in-chat", onMentionFile);
		return () =>
			window.removeEventListener("oqto:mention-file-in-chat", onMentionFile);
	}, [insertFileMentionAtCursor]);

	const handleStop = useCallback(async () => {
		await abort();
	}, [abort]);

	// Voice mode handlers
	const handleVoiceConversation = useCallback(() => {
		setVoiceMode("conversation");
		dictation.start();
	}, [dictation]);

	const handleVoiceDictation = useCallback(async () => {
		setVoiceMode("dictation");
		await dictation.start();
	}, [dictation]);

	const handleVoiceStop = useCallback(() => {
		// Use cancel() to stop without auto-send - user clicked X
		dictation.cancel();
		setVoiceMode(null);
	}, [dictation]);

	const hasVoice = !!features?.voice;
	const { t } = useTranslation();

	const tempId = sessionMeta ? getTempIdFromSession(sessionMeta) : null;
	const tempIdLabel = formatTempId(tempId);
	const formattedDate = sessionMeta?.updated_at
		? formatSessionDate(sessionMeta.updated_at)
		: sessionMeta?.created_at
			? formatSessionDate(sessionMeta.created_at)
			: null;

	const sessionTitle = (() => {
		if (sessionMeta?.title?.trim()) {
			return getDisplayPiTitle(sessionMeta);
		}
		return assistantName?.trim() || t("chat.title");
	})();

	const modelLabel = currentModelInfo
		? currentModelInfo.name?.trim() ||
			`${currentModelInfo.provider}/${currentModelInfo.id}`
		: (currentModelRef ?? selectedModelRef ?? null);
	const isWorking = isStreaming || isAwaitingResponse;
	const statusLabel = isWorking
		? t("chat.working_label")
		: t("chat.idle_label");

	const handleDownloadSessionMarkdown = useCallback(() => {
		if (messages.length === 0) {
			toast.info("No messages to download yet.");
			return;
		}

		const markdown = [
			`# ${sessionTitle}`,
			"",
			`- Exported: ${new Date().toISOString()}`,
			workspacePath ? `- Workspace: ${workspacePath}` : null,
			selectedSessionId ? `- Session ID: ${selectedSessionId}` : null,
			"",
			...messages.flatMap((message) => {
				const heading = `## ${message.role.toUpperCase()} · ${new Date(message.timestamp).toISOString()}`;
				const partLines = message.parts.flatMap((part) => {
					switch (part.type) {
						case "text":
							return [stripAnsiSequences(part.text ?? "")];
						case "thinking":
							return ["### Thinking", "", stripAnsiSequences(part.text ?? "")];
						case "tool_call":
							return [
								`### Tool call: ${part.name}`,
								"",
								"```json",
								stringifyForMarkdown(part.input),
								"```",
							];
						case "tool_result":
							return [
								`### Tool result${part.name ? `: ${part.name}` : ""}${part.isError ? " (error)" : ""}`,
								"",
								"```",
								stringifyForMarkdown(part.output),
								"```",
							];
						case "file_ref":
							return [`- File: ${part.label ?? part.uri}`];
						case "image":
							return [`- Image: ${part.alt ?? "(no alt text)"}`];
						case "compaction":
							return [
								"### Compaction",
								"",
								stripAnsiSequences(part.text ?? ""),
							];
						case "error":
							return ["### Error", "", stripAnsiSequences(part.text ?? "")];
						default:
							return [
								`- [${part.type}] ${stringifyForMarkdown((part as Record<string, unknown>).payload ?? part)}`,
							];
					}
				});
				return [heading, "", ...partLines, ""];
			}),
		]
			.filter((line): line is string => line !== null)
			.join("\n");

		const fileName = `${safeFileStem(sessionTitle)}-${new Date().toISOString().replace(/[:.]/g, "-")}.md`;
		const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
		const url = URL.createObjectURL(blob);
		const link = document.createElement("a");
		link.href = url;
		link.download = fileName;
		document.body.append(link);
		link.click();
		link.remove();
		URL.revokeObjectURL(url);
	}, [messages, selectedSessionId, sessionTitle, workspacePath]);

	// useeffect-guardrail: allow - listens for SessionScreen header action to trigger export inside ChatView
	useEffect(() => {
		const onDownloadSessionMarkdown = () => {
			handleDownloadSessionMarkdown();
		};
		window.addEventListener(
			"oqto:download-session-markdown",
			onDownloadSessionMarkdown,
		);
		return () =>
			window.removeEventListener(
				"oqto:download-session-markdown",
				onDownloadSessionMarkdown,
			);
	}, [handleDownloadSessionMarkdown]);

	const SessionHeader = (
		<div className="pb-3 mb-3 border-b border-border pr-10">
			<div className="flex items-center justify-between gap-3">
				<div className="flex items-center gap-3 min-w-0 flex-1">
					<div className="min-w-0 flex-1">
						<div className="flex items-center gap-2">
							<h1 className="text-base sm:text-lg font-semibold text-foreground tracking-wider truncate">
								{sessionTitle}
								{sessionMeta?.readable_id?.trim() && (
									<span className="ml-2 text-sm font-mono text-muted-foreground">
										[{sessionMeta.readable_id.trim()}]
									</span>
								)}
							</h1>
							{assistantName && assistantName !== sessionTitle && (
								<span className="text-xs px-1.5 py-0.5 rounded-full text-white flex-shrink-0 bg-primary/70">
									{assistantName}
								</span>
							)}
						</div>
						<div className="flex items-center gap-2 text-xs text-foreground/60 dark:text-muted-foreground">
							{(workspacePath || tempIdLabel) && (
								<span className="font-mono truncate">
									{workspacePath?.split("/").pop()}
									{tempIdLabel && ` [${tempIdLabel}]`}
								</span>
							)}
							{(workspacePath || tempIdLabel) && formattedDate && (
								<span className="opacity-50">|</span>
							)}
							{formattedDate && (
								<span className="flex-shrink-0">{formattedDate}</span>
							)}
							{(modelLabel || statusLabel) &&
								(workspacePath || tempIdLabel || formattedDate) && (
									<span className="opacity-50">|</span>
								)}
							{modelLabel && <span className="truncate">{modelLabel}</span>}
							{modelLabel && statusLabel && (
								<span className="opacity-50">|</span>
							)}
							{statusLabel && (
								<span className="flex-shrink-0">{statusLabel}</span>
							)}
						</div>
					</div>
				</div>
				<Button
					type="button"
					variant="outline"
					size="sm"
					onClick={handleDownloadSessionMarkdown}
					className="shrink-0"
					title="Download this session as markdown"
				>
					<Download className="h-4 w-4" />
				</Button>
			</div>
			<div className="mt-2">
				<ContextWindowGauge
					inputTokens={gaugeTokens.inputTokens}
					outputTokens={gaugeTokens.outputTokens}
					maxTokens={contextWindowLimit}
					locale={locale}
					compact
				/>
			</div>
		</div>
	);

	return (
		<>
			<div className={cn("flex flex-col h-full min-h-0", className)}>
				{!hideHeader && SessionHeader}

				{/* Error banner - only show if no cached messages available */}
				{displayError && messages.length === 0 && (
					<div className="px-4 py-2 bg-destructive/10 text-destructive text-sm">
						{displayError.message}
					</div>
				)}

				{/* Messages area */}
				<div className="relative flex-1 min-h-0">
					{showTimelineTreePreview && messages.length > 0 && (
						<div className="absolute inset-0 z-10 bg-background">
							<TimelineTreeView
								messages={messages}
								currentHeadId={messages.at(-1)?.id ?? null}
								onSelectMessage={(messageId) => {
									const target = messagesContainerRef.current?.querySelector(
										`[data-message-id="${CSS.escape(messageId)}"]`,
									);
									target?.scrollIntoView({
										behavior: "smooth",
										block: "center",
									});
								}}
							/>
						</div>
					)}
					<div
						ref={messagesContainerRef}
						onScroll={handleScroll}
						className="h-full bg-muted/30 border border-border p-2 sm:p-4 overflow-y-auto scrollbar-hide [overflow-anchor:none]"
						data-spotlight="chat-timeline"
					>
						<div>
							{showSkeleton && ChatSkeleton}

							{!showSkeleton && instructionsContent && (
								<div className="mb-4 sm:mb-6">
									<InstructionsPinnedMessage
										key={normalizedWorkspacePath ?? "default"}
										content={instructionsContent}
										workspacePath={normalizedWorkspacePath}
									/>
								</div>
							)}

							{!showSkeleton &&
								historyHydrated &&
								messages.length === 0 &&
								!sendPending &&
								!isStreaming &&
								!isAwaitingResponse && (
									<div className="flex items-center gap-2 text-sm text-muted-foreground">
										<span>{t("chat.noMessages")}</span>
									</div>
								)}

							{/* Load more indicator */}
							{messages.length > visibleCount && (
								<div className="text-center text-xs text-muted-foreground py-2">
									{messages.length - visibleCount} older messages...
								</div>
							)}

							{/* Only render the last visibleCount messages for performance */}
							{!showSkeleton &&
								(() => {
									return renderedGroups.map(
										({
											group,
											groupIndex,
											groupMessageId,
											groupSurfaces,
											isWorking,
											isLastAssistantGroup,
											modelChangeRef,
										}) => {
											const modelChangeDivider = modelChangeRef ? (
												<ModelChangeDivider modelRef={modelChangeRef} />
											) : null;

											return (
												<div
													key={`${groupMessageId ?? `${group.role}-${groupIndex}`}-${groupIndex}`}
													className={groupIndex > 0 ? "mt-4 sm:mt-6" : ""}
												>
													{modelChangeDivider}
													<MessageGroupCard
														group={group}
														assistantName={assistantName}
														tempIdLabel={tempIdLabel}
														workspacePath={workspacePath}
														fileAdapter={LEGACY_CHAT_FILE_ADAPTER}
														locale={locale}
														a2uiSurfaces={groupSurfaces}
														onA2UIAction={handleA2UIAction}
														messageId={groupMessageId}
														onForkHere={
															group.role === "user"
																? () => {
																		if (
																			groupMessageId &&
																			!groupMessageId.startsWith("history-")
																		) {
																			void handleForkAtEntry(groupMessageId);
																			return;
																		}
																		setForkListOpen(true);
																		void loadForkPoints();
																	}
																: undefined
														}
														onFileReferenceOpen={onFileReferenceOpen}
														hideRecoveredErrors={hideRecoveredErrors}
														freezeStreamingUpdates={isUserScrolled}
														streamingPresentationMode={
															streamingPresentationMode
														}
														showWorkingIndicator={
															isWorking && isLastAssistantGroup
														}
													/>
												</div>
											);
										},
									);
								})()}

							{/* Orphaned A2UI surfaces (no valid anchor) */}
							{orphanedSurfaces.length > 0 && (
								<div className="space-y-2 mt-4">
									{orphanedSurfaces.map((surface) => (
										<A2UICallCard
											key={surface.surfaceId}
											surfaceId={surface.surfaceId}
											messages={surface.messages}
											blocking={surface.blocking}
											requestId={surface.requestId}
											answered={surface.answered}
											answeredAction={surface.answeredAction}
											answeredAt={surface.answeredAt}
											onAction={handleA2UIAction}
										/>
									))}
								</div>
							)}
							{/* Inline error/retry indicator - shows below messages */}
							{displayError && messages.length > 0 && !isStreaming && (
								<div className="mt-2 px-3 py-2 rounded-md bg-destructive/10 text-destructive text-sm border border-destructive/20">
									{displayError.message}
								</div>
							)}
						</div>
						<div ref={messagesEndRef} />
					</div>

					{/* Jump to bottom — slim bar above input (overlay to avoid layout shift) */}
					{isUserScrolled && (
						<button
							type="button"
							onClick={handleScrollToBottom}
							className="absolute bottom-0 left-0 right-0 z-10 bg-primary/50 cursor-pointer hover:bg-primary transition-colors"
							style={{
								height: "4px",
								minHeight: "4px",
								padding: 0,
								lineHeight: 0,
							}}
							title="Jump to bottom"
						/>
					)}
				</div>

				{/* Hidden file input */}
				<input
					ref={fileInputRef}
					type="file"
					multiple
					className="hidden"
					onChange={(e) => handleFileUpload(e.target.files)}
				/>

				{/* Chat input - canonical chat input */}
				<div className="chat-input-container flex flex-col gap-1 bg-muted/30 border border-border px-2 py-1 mt-2">
					<div className="flex items-center gap-2">
						{/* File upload button */}
						<button
							type="button"
							onClick={() => fileInputRef.current?.click()}
							disabled={isUploading}
							className="flex-shrink-0 h-8 px-2 flex items-center justify-center text-muted-foreground hover:text-foreground disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
							title={t("chat.uploadFile")}
						>
							{isUploading ? (
								<Loader2 className="size-4 animate-spin" />
							) : (
								<Paperclip className="size-4" />
							)}
						</button>

						{/* Voice menu button */}
						{hasVoice && (
							<VoiceMenuButton
								activeMode={voiceMode}
								voiceState={dictation.isActive ? "listening" : "idle"}
								onConversation={handleVoiceConversation}
								onDictation={handleVoiceDictation}
								onStop={handleVoiceStop}
								locale={locale}
								className="flex-shrink-0"
							/>
						)}

						{/* Textarea wrapper with slash command popup */}
						<div
							className="flex-1 relative flex flex-col min-h-[32px]"
							data-spotlight="chat-input"
						>
							<SlashCommandPopup
								commands={slashCommands}
								query={slashQueryRef.current.command}
								isOpen={
									showSlashPopup &&
									slashQueryRef.current.isSlash &&
									!slashQueryRef.current.args
								}
								onSelect={(cmd) => {
									const sq = slashQueryRef.current;
									if (builtInCommandNames.has(cmd.name)) {
										runSlashCommand(cmd.name, sq.args)
											.then((result) => {
												if (result.clearInput) {
													setInput("");
													setFileAttachments([]);
													if (inputRef.current) {
														inputRef.current.style.height = "auto";
													}
												}
												setShowSlashPopup(false);
											})
											.catch((err) => {
												setCommandError(
													err instanceof Error
														? err
														: new Error("Command failed"),
												);
												setShowSlashPopup(false);
											});
										return;
									}

									if (sq.args.trim()) {
										send(`/${cmd.name} ${sq.args.trim()}`)
											.then(() => {
												setInput("");
												setFileAttachments([]);
												if (inputRef.current) {
													inputRef.current.style.height = "auto";
												}
												setShowSlashPopup(false);
											})
											.catch((err) => {
												setCommandError(
													err instanceof Error
														? err
														: new Error("Command failed"),
												);
												setShowSlashPopup(false);
											});
									} else {
										setInput(`/${cmd.name} `);
										inputRef.current?.focus();
										setShowSlashPopup(false);
									}
								}}
								onClose={() => setShowSlashPopup(false)}
							/>
							<FileMentionPopup
								query={fileMentionQuery}
								isOpen={showFileMentionPopup}
								workspacePath={workspacePath ?? null}
								onSelect={handleFileSelect}
								onClose={() => {
									setShowFileMentionPopup(false);
									setFileMentionQuery("");
								}}
							/>

							{showPromptQueueDebug && promptQueue.length > 0 && (
								<div className="mb-2 rounded-md border border-primary/20 bg-primary/5 p-2">
									<div className="flex items-center justify-between text-xs text-muted-foreground mb-2">
										<span>Runner prompt queue</span>
										<span>{promptQueue.length}</span>
									</div>
									<div className="space-y-1 max-h-28 overflow-y-auto pr-1">
										{promptQueue.map((item, index) => (
											<div
												key={`${item.bridgeSeq ?? item.clientId}-${index}`}
												className="flex items-center justify-between rounded-md bg-background/70 px-2 py-1 text-xs"
											>
												<span className="text-muted-foreground">
													#{index + 1}
												</span>
												<span className="truncate mx-2 flex-1">
													{item.clientId}
												</span>
												<span className="uppercase text-[10px] text-muted-foreground">
													{item.intent}
												</span>
											</div>
										))}
									</div>
								</div>
							)}

							{queuedMessages.length > 0 && (
								<div className="mb-2 rounded-md border border-border/60 bg-muted/20 p-2">
									<div className="flex items-center justify-between text-xs text-muted-foreground mb-2">
										<span>Queued messages</span>
										<Button
											type="button"
											variant="ghost"
											size="sm"
											className="h-6 px-2 text-xs text-muted-foreground hover:text-foreground"
											onClick={handleQueueClear}
										>
											Clear
										</Button>
									</div>
									<div className="space-y-1 max-h-32 overflow-y-auto pr-1">
										{queuedMessages.map((item, index) => (
											<div
												key={item.id}
												className="flex items-start gap-2 rounded-md bg-muted/30 p-1.5"
											>
												<span className="mt-1 text-[10px] text-muted-foreground w-4 text-right">
													{index + 1}
												</span>
												<textarea
													value={item.text}
													onChange={(e) =>
														handleQueueEdit(item.id, e.target.value)
													}
													onInput={(e) => {
														const el = e.currentTarget;
														el.style.height = "auto";
														el.style.height = `${Math.min(el.scrollHeight, 120)}px`;
													}}
													rows={1}
													className="flex-1 bg-transparent text-xs leading-4 resize-none outline-none"
												/>
												<div className="flex flex-col gap-1">
													<Button
														type="button"
														variant="ghost"
														size="icon"
														className="h-6 w-6 text-muted-foreground hover:text-foreground"
														disabled={index === 0}
														onClick={() => handleQueueMove(item.id, -1)}
													>
														<ArrowUp className="h-3 w-3" />
													</Button>
													<Button
														type="button"
														variant="ghost"
														size="icon"
														className="h-6 w-6 text-muted-foreground hover:text-foreground"
														disabled={index === queuedMessages.length - 1}
														onClick={() => handleQueueMove(item.id, 1)}
													>
														<ArrowDown className="h-3 w-3" />
													</Button>
													<Button
														type="button"
														variant="ghost"
														size="icon"
														className="h-6 w-6 text-muted-foreground hover:text-foreground"
														onClick={() => handleQueueRemove(item.id)}
													>
														<Trash2 className="h-3 w-3" />
													</Button>
												</div>
											</div>
										))}
									</div>
								</div>
							)}

							{/* File attachment chips */}
							{fileAttachments.length > 0 && (
								<div className="flex flex-wrap gap-1 mb-1">
									{fileAttachments.map((attachment) => (
										<FileAttachmentChip
											key={attachment.id}
											attachment={attachment}
											onRemove={() => {
												setFileAttachments((prev) =>
													prev.filter((a) => a.id !== attachment.id),
												);
											}}
										/>
									))}
								</div>
							)}

							{hasVoice && dictation.isActive ? (
								<DictationOverlay
									open
									value={inputValueRef.current}
									liveTranscript={dictation.liveTranscript}
									placeholder={t("chat.speakNow")}
									vadProgress={dictation.vadProgress}
									autoSend={dictation.autoSendEnabled}
									onAutoSendChange={dictation.setAutoSendEnabled}
									onStop={handleVoiceStop}
									onChange={handleInputChange}
									onKeyDown={handleKeyDown}
									onPaste={(e) => {
										// Handle pasted files
										const items = e.clipboardData?.items;
										if (!items) return;

										const files: File[] = [];
										let imageIndex = 0;
										for (const item of Array.from(items)) {
											if (item.kind === "file") {
												const file = item.getAsFile();
												if (file) {
													// Rename generic clipboard image names to be unique
													const isGenericName =
														/^image\.(png|gif|jpg|jpeg|webp)$/i.test(file.name);
													if (isGenericName) {
														const ext = file.name.split(".").pop() || "png";
														const uniqueName = `pasted-image-${Date.now()}-${imageIndex++}.${ext}`;
														const renamedFile = new File([file], uniqueName, {
															type: file.type,
														});
														files.push(renamedFile);
													} else {
														files.push(file);
													}
												}
											}
										}

										if (files.length > 0) {
											e.preventDefault();
											const dataTransfer = new DataTransfer();
											for (const file of files) {
												dataTransfer.items.add(file);
											}
											handleFileUpload(dataTransfer.files);
										}
									}}
									onFocus={(e) => {
										// Scroll input into view on mobile when keyboard opens
										setTimeout(() => {
											e.target.scrollIntoView({
												behavior: "smooth",
												block: "nearest",
											});
										}, 300);
									}}
								/>
							) : (
								<textarea
									ref={inputRef}
									autoComplete="off"
									autoCorrect="off"
									autoCapitalize="sentences"
									spellCheck={false}
									enterKeyHint="send"
									data-form-type="other"
									placeholder={t("chat.placeholder")}
									defaultValue={inputInitialValue}
									onChange={handleInputChange}
									onKeyDown={handleKeyDown}
									onPaste={(e) => {
										// Handle pasted files
										const items = e.clipboardData?.items;
										if (!items) return;

										const files: File[] = [];
										let imageIndex = 0;
										for (const item of Array.from(items)) {
											if (item.kind === "file") {
												const file = item.getAsFile();
												if (file) {
													// Rename generic clipboard image names to be unique
													const isGenericName =
														/^image\.(png|gif|jpg|jpeg|webp)$/i.test(file.name);
													if (isGenericName) {
														const ext = file.name.split(".").pop() || "png";
														const uniqueName = `pasted-image-${Date.now()}-${imageIndex++}.${ext}`;
														const renamedFile = new File([file], uniqueName, {
															type: file.type,
														});
														files.push(renamedFile);
													} else {
														files.push(file);
													}
												}
											}
										}

										if (files.length > 0) {
											e.preventDefault();
											const dataTransfer = new DataTransfer();
											for (const file of files) {
												dataTransfer.items.add(file);
											}
											handleFileUpload(dataTransfer.files);
										}
									}}
									onFocus={(e) => {
										// Scroll input into view on mobile when keyboard opens
										setTimeout(() => {
											e.target.scrollIntoView({
												behavior: "smooth",
												block: "nearest",
											});
										}, 300);
									}}
									rows={1}
									className="w-full bg-transparent border-none outline-none text-foreground placeholder:text-muted-foreground text-sm resize-none py-1.5 leading-5 max-h-[200px] overflow-y-auto"
								/>
							)}
						</div>

						{/* Stop button - only shown when streaming */}
						{isStreaming && (
							<Button
								type="button"
								onClick={handleStop}
								className="stop-button-animated flex-shrink-0 h-8 px-2 flex items-center justify-center text-destructive hover:text-destructive/80 transition-colors bg-transparent hover:bg-transparent"
								variant="ghost"
								size="icon"
								title={t("chat.stopAgent")}
							>
								<span className="stop-button-ring" aria-hidden>
									<svg viewBox="0 0 100 100" role="presentation">
										<circle
											cx="50"
											cy="50"
											r="46"
											fill="none"
											stroke="currentColor"
											strokeWidth="3"
											strokeLinecap="round"
											strokeDasharray="72 216"
											opacity="0.8"
										/>
									</svg>
								</span>
								<StopCircle className="w-4 h-4" />
							</Button>
						)}

						{/* Send button */}
						<Button
							type="button"
							data-dictation-send
							onClick={handleSendClick}
							onPointerDown={handleSendPointerDown}
							onPointerUp={handleSendPointerUp}
							onPointerCancel={handleSendPointerUp}
							onPointerLeave={handleSendPointerLeave}
							disabled={!canSendInput && fileAttachments.length === 0}
							className="flex-shrink-0 h-8 px-2 flex items-center justify-center text-muted-foreground hover:text-foreground disabled:opacity-50 disabled:cursor-not-allowed transition-colors bg-transparent hover:bg-transparent"
							variant="ghost"
							size="icon"
						>
							<Send className="w-4 h-4" />
						</Button>
					</div>
				</div>

				<Dialog open={forkListOpen} onOpenChange={setForkListOpen}>
					<DialogContent className="sm:max-w-2xl">
						<DialogHeader>
							<DialogTitle>
								{t("chat.forkListTitle", "Fork from message")}
							</DialogTitle>
							<DialogDescription>
								{t(
									"chat.forkListDescription",
									"Choose a user message to copy into a new independent session.",
								)}
							</DialogDescription>
						</DialogHeader>
						<div className="max-h-[50vh] overflow-y-auto space-y-2 pr-1">
							{forkPointsLoading ? (
								<div className="flex items-center gap-2 text-sm text-muted-foreground py-2">
									<Loader2 className="w-4 h-4 animate-spin" />
									{t("chat.loadingForkPoints", "Loading fork points...")}
								</div>
							) : forkPoints.length === 0 ? (
								<div className="text-sm text-muted-foreground py-2">
									{t(
										"chat.noForkPoints",
										"No forkable user messages found in this session.",
									)}
								</div>
							) : (
								forkPoints.map((point) => (
									<button
										key={point.entry_id}
										type="button"
										onClick={() => {
											void handleForkAtEntry(point.entry_id);
										}}
										disabled={forkingEntryId === point.entry_id}
										className="w-full text-left border border-border rounded px-3 py-2 hover:bg-muted/60 disabled:opacity-60"
									>
										<div className="flex items-center justify-between gap-3">
											<span className="text-xs text-muted-foreground font-mono">
												{point.entry_id.slice(0, 8)}
											</span>
											{forkingEntryId === point.entry_id && (
												<Loader2 className="w-3.5 h-3.5 animate-spin text-muted-foreground" />
											)}
										</div>
										<div className="text-sm text-foreground mt-1 line-clamp-3">
											{point.preview ||
												t("chat.emptyForkPreview", "(no preview)")}
										</div>
									</button>
								))
							)}
						</div>
						<DialogFooter>
							<Button variant="outline" onClick={() => setForkListOpen(false)}>
								{t("common.close", "Close")}
							</Button>
						</DialogFooter>
					</DialogContent>
				</Dialog>
			</div>
		</>
	);
}

// ============================================================================
// Model change divider
// ============================================================================

/** Extract a model identifier from the first assistant message in a group that has model info.
 * hstry stores model as "provider/model" or just "model"; live messages have separate fields. */
function getGroupModelRef(group: { messages: DisplayMessage[] }):
	| string
	| null {
	for (const msg of group.messages) {
		if (msg.model) {
			// If provider is separate, combine them
			if (msg.provider) return `${msg.provider}/${msg.model}`;
			// hstry may already store "provider/model" in the model field
			return msg.model;
		}
	}
	return null;
}

/** Small inline divider shown when the model changes between assistant responses. */
function ModelChangeDivider({ modelRef }: { modelRef: string }) {
	// Show a short version of the model name
	const parts = modelRef.split("/");
	const display = parts.length >= 2 ? parts.slice(1).join("/") : modelRef;
	return (
		<div className="flex items-center gap-2 py-1 mb-2">
			<div className="flex-1 border-t border-border/40" />
			<span className="text-[10px] text-muted-foreground/60 font-mono">
				switched to {display}
			</span>
			<div className="flex-1 border-t border-border/40" />
		</div>
	);
}

// ============================================================================
// Message grouping
// ============================================================================
