use super::super::*;

pub(crate) async fn handle_request(runner: &Runner, req: RunnerRequest) -> RunnerResponse {
    match req {
        RunnerRequest::PiCreateSession(r) => runner.pi_create_session(r).await,
        RunnerRequest::PiCloseSession(r) => runner.pi_close_session(r).await,
        RunnerRequest::PiDeleteSession(r) => runner.pi_delete_session(r).await,
        RunnerRequest::PiNewSession(r) => runner.pi_new_session(r).await,
        RunnerRequest::PiSwitchSession(r) => runner.pi_switch_session(r).await,
        RunnerRequest::PiListSessions => runner.pi_list_sessions().await,
        RunnerRequest::PiSubscribe(_) => error_response(
            ErrorCode::Internal,
            "PiSubscribe must be handled via streaming",
        ),
        RunnerRequest::PiUnsubscribe(r) => runner.pi_unsubscribe(r).await,
        RunnerRequest::PiPrompt(r) => runner.pi_prompt(r).await,
        RunnerRequest::PiSteer(r) => runner.pi_steer(r).await,
        RunnerRequest::PiFollowUp(r) => runner.pi_follow_up(r).await,
        RunnerRequest::PiAbort(r) => runner.pi_abort(r).await,
        RunnerRequest::PiGetState(r) => runner.pi_get_state(r).await,
        RunnerRequest::PiGetMessages(r) => runner.pi_get_messages(r).await,
        RunnerRequest::PiGetSessionStats(r) => runner.pi_get_session_stats(r).await,
        RunnerRequest::PiGetLastAssistantText(r) => runner.pi_get_last_assistant_text(r).await,
        RunnerRequest::PiSetModel(r) => runner.pi_set_model(r).await,
        RunnerRequest::PiCycleModel(r) => runner.pi_cycle_model(r).await,
        RunnerRequest::PiGetAvailableModels(r) => runner.pi_get_available_models(r).await,
        RunnerRequest::PiSetThinkingLevel(r) => runner.pi_set_thinking_level(r).await,
        RunnerRequest::PiCycleThinkingLevel(r) => runner.pi_cycle_thinking_level(r).await,
        RunnerRequest::PiCompact(r) => runner.pi_compact(r).await,
        RunnerRequest::PiSetAutoCompaction(r) => runner.pi_set_auto_compaction(r).await,
        RunnerRequest::PiSetSteeringMode(r) => runner.pi_set_steering_mode(r).await,
        RunnerRequest::PiSetFollowUpMode(r) => runner.pi_set_follow_up_mode(r).await,
        RunnerRequest::PiSetAutoRetry(r) => runner.pi_set_auto_retry(r).await,
        RunnerRequest::PiAbortRetry(r) => runner.pi_abort_retry(r).await,
        RunnerRequest::PiFork(r) => runner.pi_fork(r).await,
        RunnerRequest::PiGetForkMessages(r) => runner.pi_get_fork_messages(r).await,
        RunnerRequest::PiSetSessionName(r) => runner.pi_set_session_name(r).await,
        RunnerRequest::PiExportHtml(r) => runner.pi_export_html(r).await,
        RunnerRequest::AgentGetCommands(r) => runner.agent_get_commands(r).await,
        RunnerRequest::PiBash(r) => runner.pi_bash(r).await,
        RunnerRequest::PiAbortBash(r) => runner.pi_abort_bash(r).await,
        RunnerRequest::PiExtensionUiResponse(r) => runner.pi_extension_ui_response(r).await,
        _ => error_response(ErrorCode::InvalidRequest, "Invalid pi request"),
    }
}
