#!/usr/bin/env bash
set -euo pipefail

PROXMOX_HOST="${PROXMOX_HOST:-proxmox}"
PROXMOX_NODE="${PROXMOX_NODE:-wismut}"

OQTO_E2E_MODE="${OQTO_E2E_MODE:-lxc}"

VM_EPHEMERAL="${VM_EPHEMERAL:-114}"
VM_CONTINUOUS="${VM_CONTINUOUS:-115}"
OQTO_E2E_SNAPSHOT="${OQTO_E2E_SNAPSHOT:-e2e-clean}"

OQTO_E2E_LXC_TEMPLATE="${OQTO_E2E_LXC_TEMPLATE:-local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst}"
OQTO_E2E_STORAGE="${OQTO_E2E_STORAGE:-local-lvm}"
OQTO_E2E_BRIDGE="${OQTO_E2E_BRIDGE:-vmbr0}"
OQTO_E2E_ROOTFS_SIZE="${OQTO_E2E_ROOTFS_SIZE:-32}"
OQTO_E2E_CT_CORES="${OQTO_E2E_CT_CORES:-2}"
OQTO_E2E_CT_MEMORY_MB="${OQTO_E2E_CT_MEMORY_MB:-4096}"
OQTO_E2E_CT_SWAP_MB="${OQTO_E2E_CT_SWAP_MB:-1024}"

OQTO_E2E_SSH_USER="${OQTO_E2E_SSH_USER:-oqto}"
OQTO_E2E_SSH_KEY="${OQTO_E2E_SSH_KEY:-$HOME/.ssh/oqto-test-key}"
OQTO_E2E_REPO_DIR="${OQTO_E2E_REPO_DIR:-/home/${OQTO_E2E_SSH_USER}/oqto}"

OQTO_E2E_HTTP_PORT="${OQTO_E2E_HTTP_PORT:-8080}"
OQTO_E2E_HOST_CHECK_PATH="${OQTO_E2E_HOST_CHECK_PATH:-/api/health}"
OQTO_E2E_WAIT_SECS="${OQTO_E2E_WAIT_SECS:-180}"

OQTO_E2E_IP_EPHEMERAL="${OQTO_E2E_IP_EPHEMERAL:-}"
OQTO_E2E_IP_CONTINUOUS="${OQTO_E2E_IP_CONTINUOUS:-}"

OQTO_E2E_SETUP_CONFIG="${OQTO_E2E_SETUP_CONFIG:-scripts/e2e/configs/oqto.setup.toml}"
OQTO_E2E_SETUP_URL="${OQTO_E2E_SETUP_URL:-}"
OQTO_E2E_ADMIN_USERNAME="${OQTO_E2E_ADMIN_USERNAME:-e2e-admin}"
OQTO_E2E_SUDO_PASSWORD="${OQTO_E2E_SUDO_PASSWORD:-}"
OQTO_E2E_ENABLE_NOPASSWD="${OQTO_E2E_ENABLE_NOPASSWD:-true}"
OQTO_E2E_FORCE_SOURCE_BUILD="${OQTO_E2E_FORCE_SOURCE_BUILD:-true}"
OQTO_E2E_CARGO_BUILD_JOBS="${OQTO_E2E_CARGO_BUILD_JOBS:-1}"
OQTO_E2E_RELEASE_LTO="${OQTO_E2E_RELEASE_LTO:-false}"
OQTO_E2E_RELEASE_CODEGEN_UNITS="${OQTO_E2E_RELEASE_CODEGEN_UNITS:-4}"

SCRIPTS_E2E_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OQTO_E2E_LOG_DIR="${OQTO_E2E_LOG_DIR:-${SCRIPTS_E2E_DIR}/logs}"
