# ==============================================================================
# Linux User Isolation Setup
# ==============================================================================

# Global variable to track if linux user isolation is enabled
LINUX_USERS_ENABLED="false"

setup_linux_user_isolation() {
  if [[ "$LINUX_USERS_ENABLED" != "true" ]]; then
    return 0
  fi

  log_step "Setting up Linux user isolation"

  local octo_group="oqto"
  local user_prefix="oqto_"
  local server_user

  # Determine who will run the backend:
  # - For system service (multi-user production): use 'oqto' system user
  # - For user service (development): use current user
  if [[ "${MULTI_USER:-false}" == "true" ]] && [[ "$OS" == "linux" ]]; then
    # Production multi-user mode: backend runs as 'oqto' system user
    server_user="oqto"
    ensure_octo_system_user
  else
    # Development mode: backend runs as current user
    server_user=$(whoami)
  fi

  log_info "Sudoers rules will be configured for user: $server_user"

  # 1. Create the oqto group
  if ! getent group "$octo_group" &>/dev/null; then
    log_info "Creating group '$octo_group'..."
    if ! sudo groupadd "$octo_group"; then
      log_error "Failed to create group '$octo_group'"
      return 1
    fi
    log_success "Group '$octo_group' created"
  else
    log_success "Group '$octo_group' already exists"
  fi

  # 2. Add the server user to the oqto group
  log_info "Adding user '$server_user' to group '$octo_group'..."
  if ! sudo usermod -aG "$octo_group" "$server_user"; then
    log_warn "Failed to add user to group (may need to re-login)"
  else
    log_success "User '$server_user' added to group '$octo_group'"
  fi

  # 3. Create sudoers file for multi-user process management
  log_info "Configuring sudoers for multi-user process management..."

  local sudoers_file="/etc/sudoers.d/oqto-multiuser"
  # Note: uid_start comes from config, default 2000
  local uid_start="${OQTO_UID_START:-2000}"
  # UID regex: match 2000-60000 range (avoids system UIDs below and nobody/reserved above)
  # [2-9][0-9]{3} matches 2000-9999, [1-5][0-9]{4} matches 10000-59999, 60000 exact
  local uid_regex="([2-9][0-9][0-9][0-9]|[1-5][0-9][0-9][0-9][0-9]|60000)"

  local sudoers_content
  sudoers_content=$(
    cat <<SUDOERS_EOF
# Oqto Multi-User Process Isolation - SECURE VERSION
# Generated by setup.sh on $(date)
# Allows the oqto server user to manage isolated user accounts
#
# SECURITY: Uses regex patterns (^...\$) to prevent privilege escalation.
# - UIDs restricted to ${uid_start}-60000 range (avoids system UIDs and nobody/reserved)
# - Usernames must start with ${user_prefix} prefix
# - Workspace chown restricted to ${user_prefix}* home directories only
# Requires sudo 1.9.10+ for regex support.

# Group management - only create the ${octo_group} group (safe - fixed value)
Cmnd_Alias OQTO_GROUPADD = /usr/sbin/groupadd ${octo_group}

# User creation - RESTRICTED to safe UID range and ${user_prefix} prefix
# Regex matches: -u NNNN -g ${octo_group} -s /bin/bash -m/-M -c COMMENT USERNAME
# UID must be in ${uid_start}-60000 range, username must start with ${user_prefix}
# GECOS format: "Oqto platform user: USER_ID" - use .* to match including spaces
Cmnd_Alias OQTO_USERADD = \\
    /usr/sbin/useradd ^-u ${uid_regex} -g ${octo_group} -s /bin/bash -m -c .* ${user_prefix}[a-z0-9_-]+\$, \\
    /usr/sbin/useradd ^-u ${uid_regex} -g ${octo_group} -s /bin/bash -M -c .* ${user_prefix}[a-z0-9_-]+\$

# User deletion - only ${user_prefix} users, no home removal (-r flag not allowed)
Cmnd_Alias OQTO_USERDEL = /usr/sbin/userdel ^${user_prefix}[a-z0-9_-]+\$

# Directory creation for runner sockets - RESTRICTED path (no path traversal)
Cmnd_Alias OQTO_MKDIR = /bin/mkdir ^-p /run/oqto/runner-sockets/${user_prefix}[a-z0-9_-]+\$

# Runner socket ownership - RESTRICTED to exact paths
Cmnd_Alias OQTO_CHOWN_RUNNER = \\
    /usr/bin/chown ^${user_prefix}[a-z0-9_-]+\\:${octo_group} /run/oqto/runner-sockets/${user_prefix}[a-z0-9_-]+\$

# Workspace ownership - RESTRICTED to ${user_prefix} user home directories ONLY
# SECURITY: Only allows chown on /home/${user_prefix}*/... NOT on other users' homes
# The regex ensures the path starts with /home/${user_prefix} to prevent privilege escalation
Cmnd_Alias OQTO_CHOWN_WORKSPACE = \\
    /usr/bin/chown ^-R ${user_prefix}[a-z0-9_-]+\\:${octo_group} /home/${user_prefix}[a-z0-9_-]+(/[^.][^/]*)*\$

# Permissions for runner socket directories
Cmnd_Alias OQTO_CHMOD_RUNNER = /usr/bin/chmod ^2770 /run/oqto/runner-sockets/${user_prefix}[a-z0-9_-]+\$

# systemd linger - only for ${user_prefix} users
Cmnd_Alias OQTO_LINGER = /usr/bin/loginctl ^enable-linger ${user_prefix}[a-z0-9_]+\$

# Start user systemd instance - RESTRICTED to ${user_prefix} user UIDs
Cmnd_Alias OQTO_START_USER = /usr/bin/systemctl ^start user@${uid_regex}\\.service\$

# User management - group and user creation
${server_user} ALL=(root) NOPASSWD: OQTO_GROUPADD, OQTO_USERADD

# systemd user management - enable/start oqto-runner as ${user_prefix}* users
Cmnd_Alias OQTO_RUNNER_SYSTEMCTL = \\
    /usr/bin/systemctl --user enable --now oqto-runner, \\
    /usr/bin/systemctl --user start oqto-runner, \\
    /usr/bin/systemctl --user enable oqto-runner
${server_user} ALL=(${user_prefix}*) NOPASSWD: OQTO_RUNNER_SYSTEMCTL

# Runner socket directory setup and workspace ownership
${server_user} ALL=(root) NOPASSWD: OQTO_MKDIR, OQTO_CHOWN_RUNNER, OQTO_CHOWN_WORKSPACE, OQTO_CHMOD_RUNNER

# User systemd management
${server_user} ALL=(root) NOPASSWD: OQTO_START_USER, OQTO_LINGER
SUDOERS_EOF
  )

  # Write sudoers file (use visudo -c to validate)
  echo "$sudoers_content" | sudo tee "$sudoers_file" >/dev/null
  sudo chmod 440 "$sudoers_file"

  # Validate the sudoers file
  if sudo visudo -c -f "$sudoers_file" &>/dev/null; then
    log_success "Sudoers file created: $sudoers_file"
  else
    log_error "Invalid sudoers file - removing it"
    sudo rm -f "$sudoers_file"
    return 1
  fi

  # 4. Create workspace base directory with proper permissions
  log_info "Creating workspace directory structure..."
  local workspace_base="/var/lib/oqto/workspaces"
  sudo mkdir -p "$workspace_base"
  sudo chown root:"$octo_group" "$workspace_base"
  sudo chmod 775 "$workspace_base"
  log_success "Workspace directory created: $workspace_base"

  # 5. Install system sandbox config (trusted, root-owned)
  log_info "Installing system sandbox configuration..."
  local sandbox_config="/etc/oqto/sandbox.toml"
  sudo mkdir -p /etc/oqto

  sudo tee "$sandbox_config" >/dev/null <<'EOF'
# Oqto Sandbox Configuration (System-wide)
# This file is owned by root and trusted by oqto-runner.
# It cannot be modified by regular users or compromised agents.

enabled = true
profile = "development"

# Paths to deny read access (sensitive files)
deny_read = [
    "~/.ssh",
    "~/.gnupg",
    "~/.aws",
    "~/.config/gcloud",
    "~/.kube",
    "/usr/bin/systemctl",
    "/bin/systemctl",
    "/usr/bin/systemd-run",
    "/bin/systemd-run",
]

# Paths to allow write access (in addition to workspace)
allow_write = [
    # Package managers / toolchains
    "~/.cargo",
    "~/.rustup",
    "~/.npm",
    "~/.bun",
    "~/.local/bin",
    # Agent tools - data directories
    "~/.local/share/skdlr",
    "~/.local/share/mmry",
    # Agent tools - config directories
    "~/.config/skdlr",
    "~/.config/mmry",
    "~/.config/byt",
    "/tmp",
]

# Paths to deny write access (takes precedence)
deny_write = [
    "/etc/oqto/sandbox.toml",
]

# Namespace isolation
isolate_network = false
isolate_pid = true
EOF

  sudo chmod 644 "$sandbox_config"
  sudo chown root:root "$sandbox_config"
  log_success "System sandbox config installed: $sandbox_config"

  # 6. Install skdlr agent config (forces oqto-sandbox wrapper)
  log_info "Installing skdlr agent configuration..."
  local skdlr_config="/etc/oqto/skdlr-agent.toml"

  sudo tee "$skdlr_config" >/dev/null <<'EOF'
# Oqto skdlr configuration for agent scheduling
# This file is owned by root and enforces oqto-sandbox for scheduled runs.

[executor]
wrapper = "oqto-sandbox"
wrapper_args = [
    "--config", "/etc/oqto/sandbox.toml",
    "--workspace", "{workdir}",
    "--"
]
EOF

  sudo chmod 644 "$skdlr_config"
  sudo chown root:root "$skdlr_config"
  log_success "Skdlr agent config installed: $skdlr_config"

  echo
  log_success "Linux user isolation configured successfully"
  echo
  echo "The following has been set up:"
  echo "  - Group '$octo_group' created"
  echo "  - User '$server_user' added to group '$octo_group'"
  echo "  - Sudoers rules for user management: $sudoers_file"
  echo "  - Workspace directory: $workspace_base"
  echo "  - System sandbox config: $sandbox_config"
  echo
  echo "When users are created, the server will:"
  echo "  1. Create a Linux user (e.g., ${user_prefix}1, ${user_prefix}2, ...)"
  echo "  2. Create their home directory with isolated workspace"
  echo "  3. Run their agent processes as that user (sandboxed)"
  echo
  echo "Security features:"
  echo "  - Processes run in bubblewrap sandbox with namespace isolation"
  echo "  - Sensitive paths (~/.ssh, ~/.aws, etc.) are blocked"
  echo "  - Sandbox config is root-owned and cannot be modified by agents"
  echo
  log_warn "You may need to log out and back in for group membership to take effect"
}

