# ==============================================================================
# Server Hardening (Linux only)
# ==============================================================================

# Check if we should run hardening
should_harden_server() {
  # Only on Linux
  [[ "$OS" != "linux" ]] && return 1

  # Only in production mode
  [[ "$PRODUCTION_MODE" != "true" ]] && return 1

  # Check if explicitly set
  if [[ "$OQTO_HARDEN_SERVER" == "yes" ]]; then
    return 0
  elif [[ "$OQTO_HARDEN_SERVER" == "no" ]]; then
    return 1
  fi

  # Prompt user
  if [[ "$NONINTERACTIVE" != "true" ]]; then
    if confirm "Apply server hardening (firewall, fail2ban, SSH hardening)?"; then
      OQTO_HARDEN_SERVER="yes"
      return 0
    fi
  fi

  return 1
}

# Install security packages
install_security_packages() {
  log_step "Installing security packages"

  case "$OS_DISTRO" in
  debian | ubuntu | pop | linuxmint)
    log_info "Installing security packages via apt..."
    apt_update_once
    sudo apt-get install -y \
      ufw \
      fail2ban \
      unattended-upgrades \
      apt-listchanges \
      logwatch \
      auditd
    ;;
  fedora | centos | rhel | rocky | alma)
    log_info "Installing security packages via dnf..."
    sudo dnf install -y \
      firewalld \
      fail2ban \
      dnf-automatic \
      audit
    ;;
  arch | manjaro | endeavouros)
    log_info "Installing security packages via pacman..."
    sudo pacman -S --noconfirm \
      ufw \
      fail2ban \
      audit
    ;;
  opensuse* | suse*)
    log_info "Installing security packages via zypper..."
    sudo zypper install -y \
      firewalld \
      fail2ban \
      audit
    ;;
  *)
    log_warn "Unknown distribution: $OS_DISTRO. Skipping security package installation."
    log_info "Please install manually: ufw/firewalld, fail2ban, auditd"
    return 1
    ;;
  esac

  log_success "Security packages installed"
}

# Configure firewall (UFW or firewalld)
configure_firewall() {
  if [[ "$OQTO_SETUP_FIREWALL" != "yes" ]]; then
    log_info "Skipping firewall configuration"
    return
  fi

  log_step "Configuring firewall"

  local ssh_port="${OQTO_SSH_PORT:-22}"
  local http_port="80"
  local https_port="443"
  local octo_port="8080"
  local frontend_port="3000"

  case "$OS_DISTRO" in
  debian | ubuntu | pop | linuxmint | arch | manjaro | endeavouros)
    if command_exists ufw; then
      log_info "Configuring UFW firewall..."

      # Set default policies
      sudo ufw default deny incoming
      sudo ufw default allow outgoing

      # Allow SSH (important: do this first!)
      sudo ufw allow "$ssh_port/tcp" comment 'SSH'

      # Allow HTTP/HTTPS for Caddy
      if [[ "$SETUP_CADDY" == "yes" ]]; then
        sudo ufw allow "$http_port/tcp" comment 'HTTP'
        sudo ufw allow "$https_port/tcp" comment 'HTTPS'
      fi

      # Allow Oqto ports (only if not using Caddy)
      if [[ "$SETUP_CADDY" != "yes" ]]; then
        sudo ufw allow "$octo_port/tcp" comment 'Oqto API'
        sudo ufw allow "$frontend_port/tcp" comment 'Oqto Frontend'
      fi

      # Enable UFW
      log_warn "Enabling UFW firewall. Make sure SSH port $ssh_port is correct!"
      echo "y" | sudo ufw enable

      sudo ufw status verbose
      log_success "UFW firewall configured"
    else
      log_warn "UFW not found, skipping firewall configuration"
    fi
    ;;
  fedora | centos | rhel | rocky | alma | opensuse* | suse*)
    if command_exists firewall-cmd; then
      log_info "Configuring firewalld..."

      sudo systemctl enable --now firewalld

      # Allow SSH
      sudo firewall-cmd --permanent --add-port="$ssh_port/tcp"

      # Allow HTTP/HTTPS for Caddy
      if [[ "$SETUP_CADDY" == "yes" ]]; then
        sudo firewall-cmd --permanent --add-service=http
        sudo firewall-cmd --permanent --add-service=https
      fi

      # Allow Oqto ports (only if not using Caddy)
      if [[ "$SETUP_CADDY" != "yes" ]]; then
        sudo firewall-cmd --permanent --add-port="$octo_port/tcp"
        sudo firewall-cmd --permanent --add-port="$frontend_port/tcp"
      fi

      sudo firewall-cmd --reload
      sudo firewall-cmd --list-all
      log_success "firewalld configured"
    else
      log_warn "firewalld not found, skipping firewall configuration"
    fi
    ;;
  esac
}

# Configure fail2ban
configure_fail2ban() {
  if [[ "$OQTO_SETUP_FAIL2BAN" != "yes" ]]; then
    log_info "Skipping fail2ban configuration"
    return
  fi

  log_step "Configuring fail2ban"

  local ssh_port="${OQTO_SSH_PORT:-22}"
  local jail_local="/etc/fail2ban/jail.local"

  # Create jail.local configuration
  sudo tee "$jail_local" >/dev/null <<EOF
# Fail2ban Configuration for Oqto Server
# Generated by setup.sh on $(date)

[DEFAULT]
# Ban duration: 1 hour
bantime = 3600

# Time window for counting failures: 10 minutes
findtime = 600

# Number of failures before ban
maxretry = 5

# Ignore localhost
ignoreip = 127.0.0.1/8 ::1

# Default action: ban with UFW/firewalld
banaction = ufw
banaction_allports = ufw

[sshd]
enabled = true
port = $ssh_port
filter = sshd
logpath = %(sshd_log)s
backend = systemd
maxretry = 3
bantime = 3600
findtime = 600
EOF

  # Use firewalld action on RHEL-based and openSUSE systems
  if [[ "$OS_DISTRO" =~ ^(fedora|centos|rhel|rocky|alma|opensuse|suse).*$ ]]; then
    sudo sed -i 's/banaction = ufw/banaction = firewallcmd-ipset/' "$jail_local"
    sudo sed -i 's/banaction_allports = ufw/banaction_allports = firewallcmd-ipset/' "$jail_local"
  fi

  # Enable and restart fail2ban
  sudo systemctl enable fail2ban
  sudo systemctl restart fail2ban

  # Wait for service to be ready, then show status
  sleep 2
  sudo fail2ban-client status 2>/dev/null || log_warn "fail2ban started but client not ready yet (check: sudo fail2ban-client status)"
  log_success "fail2ban configured"
}

# Harden SSH configuration
harden_ssh() {
  if [[ "$OQTO_HARDEN_SSH" != "yes" ]]; then
    log_info "Skipping SSH hardening"
    return
  fi

  log_step "Hardening SSH configuration"

  local ssh_port="${OQTO_SSH_PORT:-22}"
  local sshd_config_dir="/etc/ssh/sshd_config.d"
  local hardening_conf="$sshd_config_dir/00-oqto-hardening.conf"

  # Ensure sshd_config.d directory exists
  sudo mkdir -p "$sshd_config_dir"

  # Check if Include directive exists in main config
  if ! sudo grep -q "^Include /etc/ssh/sshd_config.d/\*.conf" /etc/ssh/sshd_config; then
    log_info "Adding Include directive to sshd_config..."
    sudo sed -i '1i Include /etc/ssh/sshd_config.d/*.conf' /etc/ssh/sshd_config
  fi

  # Create hardening configuration
  log_info "Creating SSH hardening configuration..."
  sudo tee "$hardening_conf" >/dev/null <<EOF
# SSH Hardening Configuration for Oqto Server
# Generated by setup.sh on $(date)
#
# This file applies security best practices for SSH.
# Edit with caution - incorrect settings can lock you out!

# Port Configuration
Port $ssh_port

# Strong Cryptography
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Enhanced Logging
LogLevel VERBOSE

# Authentication Hardening
LoginGraceTime 30s
PermitRootLogin no
StrictModes yes
MaxAuthTries 3
MaxSessions 10

# Force Public Key Authentication Only
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no

# Disable Challenge-Response (for TOTP, enable if using 2FA)
KbdInteractiveAuthentication no

# Disable Forwarding by Default
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
PermitTunnel no

# Connection Timeouts
ClientAliveInterval 300
ClientAliveCountMax 2

# Restrict to admin user if set
EOF

  # Add AllowUsers - always include the current server user (who runs setup)
  # plus the admin username if different
  local ssh_allowed_users="$(whoami)"
  if [[ -n "$ADMIN_USERNAME" && "$ADMIN_USERNAME" != "$(whoami)" ]]; then
    ssh_allowed_users="$ssh_allowed_users $ADMIN_USERNAME"
  fi
  # Also include root in case of emergency console access
  if [[ "$ssh_allowed_users" != *"root"* ]]; then
    ssh_allowed_users="$ssh_allowed_users root"
  fi
  echo "AllowUsers $ssh_allowed_users" | sudo tee -a "$hardening_conf" >/dev/null
  log_info "SSH AllowUsers: $ssh_allowed_users"

  # Validate configuration
  log_info "Validating SSH configuration..."
  if sudo sshd -t; then
    log_success "SSH configuration is valid"

    # Restart SSH
    local ssh_service="sshd"
    [[ "$OS_DISTRO" =~ ^(debian|ubuntu|pop|linuxmint)$ ]] && ssh_service="ssh"

    log_warn "Restarting SSH service. Make sure you can still connect!"
    sudo systemctl restart "$ssh_service"
    log_success "SSH hardening applied"
  else
    log_error "SSH configuration validation failed! Reverting..."
    sudo rm -f "$hardening_conf"
    return 1
  fi
}

# Configure automatic security updates
configure_auto_updates() {
  if [[ "$OQTO_SETUP_AUTO_UPDATES" != "yes" ]]; then
    log_info "Skipping automatic updates configuration"
    return
  fi

  log_step "Configuring automatic security updates"

  case "$OS_DISTRO" in
  debian | ubuntu | pop | linuxmint)
    # Configure unattended-upgrades
    sudo tee /etc/apt/apt.conf.d/50unattended-upgrades >/dev/null <<'EOF'
// Automatic security updates configuration
// Generated by Oqto setup.sh

Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Don't auto-reboot (manual control is safer for servers)
Unattended-Upgrade::Automatic-Reboot "false";

// Log to syslog
Unattended-Upgrade::SyslogEnable "true";
EOF

    sudo tee /etc/apt/apt.conf.d/20auto-upgrades >/dev/null <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
EOF

    log_success "Automatic security updates configured (Debian/Ubuntu)"
    ;;
  fedora | centos | rhel | rocky | alma)
    # Configure dnf-automatic
    sudo tee /etc/dnf/automatic.conf >/dev/null <<'EOF'
[commands]
# Only apply security updates automatically
upgrade_type = security
random_sleep = 360

# Download updates but don't apply automatically (safer)
download_updates = yes
apply_updates = no

[emitters]
system_name = oqto-server
emit_via = stdio

[email]
email_from = root@localhost
email_to = root

[command]
[command_email]
[base]
EOF

    sudo systemctl enable --now dnf-automatic.timer
    log_success "Automatic security updates configured (dnf-automatic)"
    ;;
  arch | manjaro | endeavouros)
    log_warn "Arch Linux detected. Automatic updates are not recommended for Arch."
    log_info "Consider using 'pacman -Syu' manually or setting up pacman hooks."
    ;;
  opensuse* | suse*)
    # Configure transactional-update or zypper automatic patches
    log_info "Configuring automatic security updates for openSUSE..."
    if command_exists transactional-update; then
      # For MicroOS / transactional systems
      sudo systemctl enable --now transactional-update.timer
      log_success "Transactional updates enabled"
    else
      # For traditional openSUSE
      sudo zypper install -y zypper-lifecycle-plugin
      # Enable automatic security patches
      sudo tee /etc/zypp/zypp.conf.d/auto-updates.conf >/dev/null <<'EOCONF'
# Automatic security updates
solver.onlyRequires = true
EOCONF
      log_info "openSUSE: Run 'sudo zypper patch --category security' periodically"
      log_info "Consider setting up a cron job or systemd timer for automatic patches"
    fi
    ;;
  *)
    log_warn "Unknown distribution. Skipping automatic updates configuration."
    ;;
  esac
}

# Apply kernel security parameters
harden_kernel() {
  if [[ "$OQTO_HARDEN_KERNEL" != "yes" ]]; then
    log_info "Skipping kernel hardening"
    return
  fi

  log_step "Applying kernel security parameters"

  local sysctl_conf="/etc/sysctl.d/99-oqto-hardening.conf"

  sudo tee "$sysctl_conf" >/dev/null <<'EOF'
# Kernel Security Parameters for Oqto Server
# Generated by setup.sh

# Prevent IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable ICMP redirect acceptance
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Disable ICMP redirect sending
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Enable TCP SYN cookies (protection against SYN flood attacks)
net.ipv4.tcp_syncookies = 1

# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP errors
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Log martian packets (packets with impossible addresses)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable IPv6 if not needed (uncomment if you don't use IPv6)
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1

# Prevent core dumps from being written to disk (security)
fs.suid_dumpable = 0

# Restrict kernel pointer exposure
kernel.kptr_restrict = 2

# Restrict dmesg access to root
kernel.dmesg_restrict = 1
EOF

  # Apply sysctl settings
  sudo sysctl -p "$sysctl_conf"

  log_success "Kernel security parameters applied"
}

# Enable audit logging
enable_audit_logging() {
  log_step "Enabling audit logging"

  if command_exists auditd; then
    sudo systemctl enable auditd
    sudo systemctl start auditd
    log_success "Audit logging enabled"
  else
    log_warn "auditd not installed, skipping"
  fi
}

# Main hardening function
harden_server() {
  if ! should_harden_server; then
    log_info "Server hardening skipped"
    return
  fi

  log_step "Starting server hardening"

  # Check for root/sudo
  if [[ $EUID -ne 0 ]] && ! sudo -n true 2>/dev/null; then
    log_warn "Server hardening requires sudo privileges"
    if ! confirm "Continue with server hardening (will prompt for sudo password)?"; then
      log_info "Skipping server hardening"
      return
    fi
  fi

  # Warn about SSH changes
  echo
  log_warn "╔══════════════════════════════════════════════════════════════════╗"
  log_warn "║  WARNING: SSH hardening will disable password authentication!    ║"
  log_warn "║  Make sure you have SSH key access before continuing.            ║"
  log_warn "║  SSH port will be set to: ${OQTO_SSH_PORT:-22}                   ║"
  log_warn "╚══════════════════════════════════════════════════════════════════╝"
  echo

  if [[ "$NONINTERACTIVE" != "true" ]]; then
    if ! confirm "Continue with server hardening?" "n"; then
      log_info "Server hardening cancelled"
      return
    fi
  fi

  # Install security packages
  install_security_packages

  # Configure firewall
  configure_firewall

  # Configure fail2ban
  configure_fail2ban

  # Harden SSH
  harden_ssh

  # Configure automatic updates
  configure_auto_updates

  # Harden kernel
  harden_kernel

  # Enable audit logging
  enable_audit_logging

  log_success "Server hardening complete!"
  echo
  echo "Security summary:"
  echo "  - Firewall:        $(command_exists ufw && echo 'UFW' || (command_exists firewall-cmd && echo 'firewalld' || echo 'not configured'))"
  echo "  - Fail2ban:        $(systemctl is-active fail2ban 2>/dev/null || echo 'not running')"
  echo "  - SSH hardening:   ${OQTO_HARDEN_SSH}"
  echo "  - Auto updates:    ${OQTO_SETUP_AUTO_UPDATES}"
  echo "  - Kernel hardening: ${OQTO_HARDEN_KERNEL}"
  echo "  - Audit logging:   $(systemctl is-active auditd 2>/dev/null || echo 'not running')"
  echo
}

