"use client";

import {
	type ChatSession,
	type ProjectEntry,
	deleteWorkspacePiSession,
	listChatHistory,
	newWorkspacePiSession,
	updateChatSession,
} from "@/lib/control-plane-client";
import {
	type OpenCodeSession,
	createSession,
	deleteSession,
	fetchSessions,
	updateSession,
} from "@/lib/opencode-client";
import { parseAutoGeneratedTitle, resolveReadableId } from "@/lib/session-utils";
import {
	type ReactNode,
	createContext,
	startTransition,
	useCallback,
	useContext,
	useEffect,
	useMemo,
	useRef,
	useState,
} from "react";
import { useDefaultChatContext } from "./default-chat-context";
import { useLocale } from "./ui-context";
import { useWorkspaceContext } from "./workspace-context";

export interface ChatContextValue {
	/** Chat sessions from disk (no running opencode needed) */
	chatHistory: ChatSession[];
	/** Live opencode sessions (requires running opencode) */
	opencodeSessions: OpenCodeSession[];
	selectedChatSessionId: string;
	setSelectedChatSessionId: (id: string) => void;
	selectedChatSession: OpenCodeSession | undefined;
	/** Get the selected chat from history (may not have live opencode session) */
	selectedChatFromHistory: ChatSession | undefined;
	/** Set of chat session IDs that are currently busy (agent working) */
	busySessions: Set<string>;
	/** Mark a session as busy or idle */
	setSessionBusy: (sessionId: string, busy: boolean) => void;
	refreshChatHistory: () => Promise<void>;
	refreshOpencodeSessions: () => Promise<void>;
	/** Create a placeholder chat session for instant UI feedback. */
	createOptimisticChatSession: (workspacePath?: string) => string;
	/** Remove a placeholder chat session. */
	clearOptimisticChatSession: (sessionId: string) => void;
	/** Replace a placeholder chat session with the real session id. */
	replaceOptimisticChatSession: (
		optimisticId: string,
		sessionId: string,
	) => void;
	/** Update a chat session title locally without triggering backend rename. */
	updateChatSessionTitleLocal: (sessionId: string, title: string) => void;
	createNewChat: (
		workspacePath?: string,
		options?: { optimisticId?: string },
	) => Promise<string | null>;
	deleteChatSession: (
		sessionId: string,
		baseUrlOverride?: string,
	) => Promise<boolean>;
	renameChatSession: (sessionId: string, title: string) => Promise<boolean>;
	/** Directory for the current opencode session */
	opencodeDirectory?: string;
}

// Default no-op functions for HMR resilience
const noop = () => {};
const asyncNoop = async () => null;
const asyncNoopVoid = async () => {};
const asyncNoopBool = async () => false;

const CHAT_HISTORY_CACHE_KEY = "octo:chatHistoryCache:v1";
const CHAT_HISTORY_CACHE_MAX_CHARS = 2_000_000;

function readCachedChatHistory(): ChatSession[] {
	if (typeof window === "undefined") return [];
	try {
		const raw = localStorage.getItem(CHAT_HISTORY_CACHE_KEY);
		if (!raw) return [];
		if (raw.length > CHAT_HISTORY_CACHE_MAX_CHARS) {
			localStorage.removeItem(CHAT_HISTORY_CACHE_KEY);
			return [];
		}
		const parsed = JSON.parse(raw) as ChatSession[];
		return Array.isArray(parsed) ? parsed : [];
	} catch {
		return [];
	}
}

function writeCachedChatHistory(history: ChatSession[]) {
	if (typeof window === "undefined") return;
	try {
		const encoded = JSON.stringify(history);
		if (encoded.length > CHAT_HISTORY_CACHE_MAX_CHARS) {
			localStorage.removeItem(CHAT_HISTORY_CACHE_KEY);
			return;
		}
		localStorage.setItem(CHAT_HISTORY_CACHE_KEY, encoded);
	} catch {
		// ignore storage failures
	}
}

const defaultChatContext: ChatContextValue = {
	chatHistory: [],
	opencodeSessions: [],
	selectedChatSessionId: "",
	setSelectedChatSessionId: noop,
	selectedChatSession: undefined,
	selectedChatFromHistory: undefined,
	busySessions: new Set(),
	setSessionBusy: noop,
	refreshChatHistory: asyncNoopVoid,
	refreshOpencodeSessions: asyncNoopVoid,
	createOptimisticChatSession: () => "",
	clearOptimisticChatSession: noop,
	replaceOptimisticChatSession: noop,
	updateChatSessionTitleLocal: noop,
	createNewChat: asyncNoop,
	deleteChatSession: asyncNoopBool,
	renameChatSession: asyncNoopBool,
	opencodeDirectory: undefined,
};

const ChatContext = createContext<ChatContextValue>(defaultChatContext);

export function ChatProvider({ children }: { children: ReactNode }) {
	const { locale } = useLocale();
	const {
		defaultChatActive,
		setDefaultChatActive,
		defaultChatCurrentSessionId,
		setDefaultChatCurrentSessionId,
		defaultChatWorkspacePath,
	} = useDefaultChatContext();
	const { opencodeBaseUrl, selectedWorkspaceSession, projects } =
		useWorkspaceContext();

	// Chat history from disk (no running opencode needed)
	const [chatHistory, setChatHistory] = useState<ChatSession[]>(() =>
		readCachedChatHistory(),
	);
	const chatHistoryRef = useRef<ChatSession[]>([]);
	const optimisticChatSessionsRef = useRef<Map<string, ChatSession>>(new Map());
	const optimisticSelectionRef = useRef<Map<string, string>>(new Map());
	// Track sessions that were just explicitly created - prevents refresh from overriding selection
	const recentlyCreatedSessionRef = useRef<string | null>(null);
	chatHistoryRef.current = chatHistory;

	// Live opencode sessions (requires running opencode instance)
	const [opencodeSessions, setOpencodeSessions] = useState<OpenCodeSession[]>(
		[],
	);

	const [selectedChatSessionId, setSelectedChatSessionIdRaw] = useState<string>(
		() => {
			if (typeof window !== "undefined") {
				const params = new URLSearchParams(window.location.search);
				const mockSession = params.get("mockSession");
				if (mockSession) {
					console.log("[Dev] Using mock session ID:", mockSession);
					return mockSession;
				}
				// Restore last used session
				try {
					return localStorage.getItem("octo:lastChatSessionId") || "";
				} catch {
					return "";
				}
			}
			return "";
		},
	);

	// Wrap setter to persist to localStorage
	const setSelectedChatSessionId = useCallback(
		(value: string | ((prev: string) => string)) => {
			setSelectedChatSessionIdRaw((prev) => {
				const newId = typeof value === "function" ? value(prev) : value;
				if (typeof window !== "undefined") {
					try {
						if (newId) {
							localStorage.setItem("octo:lastChatSessionId", newId);
						} else {
							localStorage.removeItem("octo:lastChatSessionId");
						}
					} catch {
						// Ignore localStorage errors
					}
				}
				return newId;
			});
		},
		[],
	);

	// Track which chat sessions are currently busy (agent working)
	const [busySessions, setBusySessions] = useState<Set<string>>(new Set());

	const setSessionBusy = useCallback((sessionId: string, busy: boolean) => {
		setBusySessions((prev) => {
			const next = new Set(prev);
			if (busy) {
				next.add(sessionId);
			} else {
				next.delete(sessionId);
			}
			return next;
		});
	}, []);

	const selectedChatSession = useMemo(() => {
		return opencodeSessions.find((s) => s.id === selectedChatSessionId);
	}, [opencodeSessions, selectedChatSessionId]);

	const selectedChatFromHistory = useMemo(() => {
		return chatHistory.find((s) => s.id === selectedChatSessionId);
	}, [chatHistory, selectedChatSessionId]);

	useEffect(() => {
		if (!selectedChatFromHistory || !defaultChatWorkspacePath) return;
		const isDefaultChatSession =
			selectedChatFromHistory.workspace_path === defaultChatWorkspacePath;

		if (isDefaultChatSession) {
			if (!defaultChatActive) setDefaultChatActive(true);
			if (defaultChatCurrentSessionId !== selectedChatFromHistory.id) {
				setDefaultChatCurrentSessionId(selectedChatFromHistory.id);
			}
		} else if (defaultChatActive) {
			setDefaultChatActive(false);
		}
	}, [
		defaultChatActive,
		defaultChatCurrentSessionId,
		defaultChatWorkspacePath,
		selectedChatFromHistory,
		setDefaultChatActive,
		setDefaultChatCurrentSessionId,
	]);

	const opencodeDirectory = useMemo(() => {
		return (
			selectedChatFromHistory?.workspace_path ??
			selectedWorkspaceSession?.workspace_path
		);
	}, [selectedChatFromHistory, selectedWorkspaceSession]);

	const resolveProjectName = useCallback(
		(workspacePath: string) => {
			const normalized = workspacePath.replace(/\\/g, "/").replace(/\/+$/, "");
			const project = projects.find(
				(entry: ProjectEntry) =>
					entry.path === workspacePath || entry.path === normalized,
			);
			if (project?.name) return project.name;
			const parts = normalized.split("/").filter(Boolean);
			if (parts.length > 0) return parts[parts.length - 1];
			return locale === "de" ? "Arbeitsbereich" : "Workspace";
		},
		[projects, locale],
	);

	const createOptimisticChatSession = useCallback(
		(workspacePath?: string) => {
			const resolvedPath =
				workspacePath?.trim() || opencodeDirectory || "global";
			const now = Date.now();
			const optimisticId = `pending-${now}-${Math.random().toString(36).slice(2, 10)}`;
			const session: ChatSession = {
				id: optimisticId,
				readable_id: resolveReadableId(optimisticId, null),
				title: locale === "de" ? "Neue Sitzung" : "New Session",
				parent_id: null,
				workspace_path: resolvedPath,
				project_name: resolveProjectName(resolvedPath),
				created_at: now,
				updated_at: now,
				version: null,
				is_child: false,
				source_path: null,
			};
			optimisticChatSessionsRef.current.set(optimisticId, session);
			optimisticSelectionRef.current.set(optimisticId, selectedChatSessionId);
			setChatHistory((prev) => [session, ...prev]);
			setSelectedChatSessionId(optimisticId);
			return optimisticId;
		},
		[
			locale,
			opencodeDirectory,
			resolveProjectName,
			selectedChatSessionId,
			setSelectedChatSessionId,
		],
	);

	const clearOptimisticChatSession = useCallback(
		(sessionId: string) => {
			if (!optimisticChatSessionsRef.current.has(sessionId)) return;
			optimisticChatSessionsRef.current.delete(sessionId);
			const previousSelection = optimisticSelectionRef.current.get(sessionId);
			optimisticSelectionRef.current.delete(sessionId);
			setChatHistory((prev) =>
				prev.filter((session) => session.id !== sessionId),
			);
			if (selectedChatSessionId === sessionId) {
				setSelectedChatSessionId(previousSelection || "");
			}
		},
		[selectedChatSessionId, setSelectedChatSessionId],
	);

	const replaceOptimisticChatSession = useCallback(
		(optimisticId: string, sessionId: string) => {
			const optimistic = optimisticChatSessionsRef.current.get(optimisticId);
			if (!optimistic) return;
			optimisticChatSessionsRef.current.delete(optimisticId);
			optimisticSelectionRef.current.delete(optimisticId);

			const updated: ChatSession = {
				...optimistic,
				id: sessionId,
				readable_id: resolveReadableId(sessionId, null),
			};

			optimisticChatSessionsRef.current.set(sessionId, updated);
			setChatHistory((prev) => {
				const filtered = prev.filter(
					(session) => session.id !== optimisticId && session.id !== sessionId,
				);
				return [updated, ...filtered];
			});
		},
		[],
	);

	// Refresh chat history from disk
	const refreshChatHistory = useCallback(async () => {
		try {
			const history = await listChatHistory({ include_children: true });
			writeCachedChatHistory(history);
			startTransition(() => {
				const optimisticSessions = Array.from(
					optimisticChatSessionsRef.current.values(),
				).filter((session) => !history.some((item) => item.id === session.id));
				setChatHistory(
					optimisticSessions.length > 0
						? [...optimisticSessions, ...history]
						: history,
				);

				if (history.length > 0 && !defaultChatActive) {
					setSelectedChatSessionId((current) => {
						// Don't override selection for recently created sessions
						if (current && current === recentlyCreatedSessionRef.current) {
							return current;
						}
						if (current && opencodeSessions.some((s) => s.id === current)) {
							return current;
						}
						if (current && history.some((s) => s.id === current))
							return current;
						if (current && optimisticChatSessionsRef.current.has(current)) {
							return current;
						}
						return history[0].id;
					});
				}
			});
		} catch (err) {
			console.error("Failed to load chat history:", err);
		}
	}, [defaultChatActive, opencodeSessions, setSelectedChatSessionId]);

	const refreshOpencodeSessions = useCallback(async () => {
		if (!opencodeBaseUrl) return;
		try {
			const sessions = await fetchSessions(opencodeBaseUrl, {
				directory: opencodeDirectory,
			});
			setOpencodeSessions(sessions);
			const history = chatHistoryRef.current;
			if (sessions.length > 0 && !defaultChatActive) {
				const sorted = [...sessions].sort(
					(a, b) => b.time.updated - a.time.updated,
				);
				setSelectedChatSessionId((current) => {
					// Don't override selection for recently created sessions
					if (current && current === recentlyCreatedSessionRef.current) {
						return current;
					}
					if (!current) return sorted[0].id;
					if (sessions.some((s) => s.id === current)) return current;
					if (history.some((s) => s.id === current)) return current;
					return sorted[0].id;
				});
			} else {
				if (!defaultChatActive) {
					setSelectedChatSessionId((current) => {
						if (current && history.some((s) => s.id === current)) {
							return current;
						}
						return current;
					});
				}
				if (history.length === 0 && !defaultChatActive) {
					const created = await createSession(
						opencodeBaseUrl,
						undefined,
						undefined,
						{ directory: opencodeDirectory },
					);
					setOpencodeSessions([created]);
					setSelectedChatSessionId(created.id);
				}
			}
		} catch (err) {
			console.error("Failed to load opencode sessions:", err);
		}
	}, [
		defaultChatActive,
		opencodeBaseUrl,
		opencodeDirectory,
		setSelectedChatSessionId,
	]);

	const createNewChat = useCallback(
		async (
			workspacePathOverride?: string,
			options?: { optimisticId?: string },
		): Promise<string | null> => {
			setDefaultChatActive(false);
			const resolvedPath =
				workspacePathOverride?.trim() ||
				opencodeDirectory ||
				selectedChatFromHistory?.workspace_path ||
				"global";
			try {
				const newState = await newWorkspacePiSession(resolvedPath);
				const sessionId = newState.session_id;
				if (!sessionId) {
					throw new Error("Pi session id missing");
				}
				if (options?.optimisticId) {
					replaceOptimisticChatSession(options.optimisticId, sessionId);
				}
				recentlyCreatedSessionRef.current = sessionId;
				setSelectedChatSessionId(sessionId);
				setTimeout(() => {
					refreshChatHistory();
					setTimeout(() => {
						if (recentlyCreatedSessionRef.current === sessionId) {
							recentlyCreatedSessionRef.current = null;
						}
					}, 100);
				}, 500);
				return sessionId;
			} catch (err) {
				if (options?.optimisticId) {
					clearOptimisticChatSession(options.optimisticId);
				}
				console.error("Failed to create new Pi chat session:", err);
				return null;
			}
		},
		[
			clearOptimisticChatSession,
			opencodeDirectory,
			replaceOptimisticChatSession,
			refreshChatHistory,
			selectedChatFromHistory,
			setSelectedChatSessionId,
			setDefaultChatActive,
		],
	);

	const deleteChatSession = useCallback(
		async (sessionId: string, baseUrlOverride?: string): Promise<boolean> => {
			const historySession = chatHistoryRef.current.find(
				(session) => session.id === sessionId,
			);
			const sourcePath = historySession?.source_path ?? "";
			const isWorkspacePi =
				sourcePath.includes("/.pi/agent/sessions") ||
				sourcePath.endsWith(".jsonl");

			if (isWorkspacePi && historySession) {
				const previousHistory = chatHistoryRef.current;
				const previousSelection = selectedChatSessionId;
				const remaining = previousHistory.filter((s) => s.id !== sessionId);
				setChatHistory(remaining);
				setSelectedChatSessionId((current) => {
					if (current !== sessionId) return current;
					return remaining[0]?.id ?? "";
				});
				try {
					await deleteWorkspacePiSession(
						historySession.workspace_path,
						sessionId,
					);
					setTimeout(() => {
						refreshChatHistory();
					}, 500);
					return true;
				} catch (err) {
					setChatHistory(previousHistory);
					if (previousSelection) {
						setSelectedChatSessionId(previousSelection);
					}
					console.error("Failed to delete Pi chat session:", err);
					return false;
				}
			}

			const baseUrl = baseUrlOverride || opencodeBaseUrl;
			if (!baseUrl) return false;
			const previousOpencode = opencodeSessions;
			const previousSelection = selectedChatSessionId;
			try {
				setOpencodeSessions((prev) => prev.filter((s) => s.id !== sessionId));
				setSelectedChatSessionId((current) => {
					if (current !== sessionId) return current;
					const remaining = previousOpencode.filter((s) => s.id !== sessionId);
					return remaining.length > 0 ? remaining[0].id : "";
				});
				await deleteSession(baseUrl, sessionId, {
					directory: opencodeDirectory,
				});
				setTimeout(() => {
					refreshChatHistory();
				}, 500);
				return true;
			} catch (err) {
				setOpencodeSessions(previousOpencode);
				if (previousSelection) {
					setSelectedChatSessionId(previousSelection);
				}
				console.error("Failed to delete chat session:", err);
				return false;
			}
		},
		[
			opencodeBaseUrl,
			opencodeDirectory,
			opencodeSessions,
			refreshChatHistory,
			selectedChatSessionId,
			setSelectedChatSessionId,
		],
	);

	const renameChatSession = useCallback(
		async (sessionId: string, title: string): Promise<boolean> => {
			try {
				if (opencodeBaseUrl) {
					try {
						const updated = await updateSession(
							opencodeBaseUrl,
							sessionId,
							{ title },
							{ directory: opencodeDirectory },
						);
						setOpencodeSessions((prev) =>
							prev.map((s) => (s.id === sessionId ? updated : s)),
						);
						setChatHistory((prev) =>
							prev.map((s) => (s.id === sessionId ? { ...s, title } : s)),
						);
						return true;
					} catch {
						// Fall through to try the history API
					}
				}

				const updated = await updateChatSession(sessionId, { title });
				setChatHistory((prev) =>
					prev.map((s) =>
						s.id === sessionId ? { ...s, title: updated.title } : s,
					),
				);
				return true;
			} catch (err) {
				console.error("Failed to rename chat session:", err);
				return false;
			}
		},
		[opencodeBaseUrl, opencodeDirectory],
	);

	const updateChatSessionTitleLocal = useCallback(
		(sessionId: string, title: string) => {
			if (!title.trim()) return;
			const parsed = parseAutoGeneratedTitle(title);
			const nextTitle = parsed.readable_id ? parsed.title : title;
			setChatHistory((prev) =>
				prev.map((s) =>
					s.id === sessionId
						? {
								...s,
								title: nextTitle,
								readable_id: parsed.readable_id ?? s.readable_id,
							}
						: s,
				),
			);
			setOpencodeSessions((prev) =>
				prev.map((s) => (s.id === sessionId ? { ...s, title: nextTitle } : s)),
			);
		},
		[],
	);

	// Initial load
	useEffect(() => {
		refreshChatHistory();
	}, [refreshChatHistory]);

	useEffect(() => {
		writeCachedChatHistory(chatHistory);
	}, [chatHistory]);

	useEffect(() => {
		refreshOpencodeSessions();
	}, [refreshOpencodeSessions]);

	const value = useMemo(
		() => ({
			chatHistory,
			opencodeSessions,
			selectedChatSessionId,
			setSelectedChatSessionId,
			selectedChatSession,
			selectedChatFromHistory,
			busySessions,
			setSessionBusy,
			refreshChatHistory,
			refreshOpencodeSessions,
			createOptimisticChatSession,
			clearOptimisticChatSession,
			replaceOptimisticChatSession,
			updateChatSessionTitleLocal,
			createNewChat,
			deleteChatSession,
			renameChatSession,
			opencodeDirectory,
		}),
		[
			chatHistory,
			opencodeSessions,
			selectedChatSessionId,
			setSelectedChatSessionId,
			selectedChatSession,
			selectedChatFromHistory,
			busySessions,
			setSessionBusy,
			refreshChatHistory,
			refreshOpencodeSessions,
			createOptimisticChatSession,
			clearOptimisticChatSession,
			replaceOptimisticChatSession,
			updateChatSessionTitleLocal,
			createNewChat,
			deleteChatSession,
			renameChatSession,
			opencodeDirectory,
		],
	);

	return <ChatContext.Provider value={value}>{children}</ChatContext.Provider>;
}

export function useChatContext() {
	return useContext(ChatContext);
}

// Convenience hooks that match the original APIs
export function useBusySessions() {
	const { busySessions, setSessionBusy } = useChatContext();
	return { busySessions, setSessionBusy };
}

export function useChatHistory() {
	const { chatHistory, refreshChatHistory } = useChatContext();
	return { chatHistory, refreshChatHistory };
}

export function useSelectedChat() {
	const {
		selectedChatSessionId,
		setSelectedChatSessionId,
		selectedChatSession,
		selectedChatFromHistory,
	} = useChatContext();
	return {
		selectedChatSessionId,
		setSelectedChatSessionId,
		selectedChatSession,
		selectedChatFromHistory,
	};
}
